#!/bin/sh
#
# Install-time build script for heap2asm.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the executable bin/heap2asm.
#
# options:
#   -o image		-- specify the name of the heap image, "heap2asm"
#			   is the default.

CMD=$0

HEAP2ASM="heap2asm"
HEAP_IMAGE=""
HERE=`pwd`
cd ../../..
THREE_UP=`pwd`
cd $HERE
BIN=${INSTALL_DIR:-$THREE_UP}/bin
MAKELIB=$BIN/build-an-executable-mythryl-heap-image


echo
echo '-----------------------------------------------------'
echo "                      build-heap2asm-app:   Starting."

#
# Process command-line options:
while [ "$#" != "0" ] ; do
    arg=$1
    shift
    case $arg in
	-o)
	    if [ "$#" = "0" ]; then
		echo "                      build-heap2asm-app:   Must supply image name for -o option"
		exit 1
	    fi
	    HEAP_IMAGE=$1; shift
	    ;;
	*)
	    echo "                      build-heap2asm-app:   Invalid argument: $arg"
	    exit 1
	    ;;
    esac
done

if [ "$HEAP_IMAGE" = "" ]; then
    HEAP_IMAGE="$HEAP2ASM"
fi

echo "                      build-heap2asm-app:   Doing:                  $MAKELIB heap2asm.lib main.main $HEAP_IMAGE"
"$MAKELIB" heap2asm.lib main.main $HEAP_IMAGE

if [ -f "$HEAP_IMAGE" ]; then

    echo "                      build-heap2asm-app:   $HEAP_IMAGE created."

    if [ -f "$BIN/$HEAP2ASM" ]; then
        echo "                      build-heap2asm-app:   Removing $BIN/$HEAP2ASM"
        rm $BIN/$HEAP2ASM
    fi

    echo "                      build-heap2asm-app:   Installing $HEAP_IMAGE as $BIN/$HEAP2ASM"
    cp "$HEAP_IMAGE" "$BIN/$HEAP2ASM"
    chmod +x "$BIN/$HEAP2ASM"
    rm "$HEAP_IMAGE"

else
    echo "                      build-heap2asm-app:   $HEAP_IMAGE not created, aborting."
    exit 1
fi


echo "                      build-heap2asm-app:   Done."
echo
echo
echo

exit 0
