#!/bin/sh

unset VERSIONTOOL_BUMP_RELEASE

../../bin/sml \$ROOT/src/lib/core/compiler/all.make7 <<stop
Alpha32UnixCMB.make () before Alpha32UnixCMB.reset () andalso
HppaUnixCMB.make () before HppaUnixCMB.reset () andalso
PPCUnixCMB.make () before PPCUnixCMB.reset () andalso
SparcUnixCMB.make () before SparcUnixCMB.reset () andalso
X86UnixCMB.make () before X86UnixCMB.reset () andalso
X86Win32CMB.make () before X86Win32CMB.reset ();
stop
