#!/bin/sh

unset VERSIONTOOL_BUMP_RELEASE

../../bin/sml \$ROOT/src/lib/core/compiler/all.make7 <<stop
Alpha32UnixCMB.make () before Alpha32UnixCMB.reset () andalso
HppaUnixCMB.make () before HppaUnixCMB.reset () andalso
PWRPC32UnixCMB.make () before PWRPC32UnixCMB.reset () andalso
Sparc32UnixCMB.make () before Sparc32UnixCMB.reset () andalso
Intel32UnixCMB.make () before Intel32UnixCMB.reset () andalso
Intel32Win32CMB.make () before Intel32Win32CMB.reset ();
stop
