#!/bin/sh
#
# Install-time build script for xkit.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/x-kit/xkit.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/x-kit/xkit.lib";
EOF

if [ -f "src/lib/x-kit/xkit.lib.frozen" ]
then
    echo "                          build-xkit-lib:   Successfully created    src/lib/x-kit/xkit.lib.frozen:"
    echo "                          build-xkit-lib:                           `ls -l src/lib/x-kit/xkit.lib.frozen`"
else
    echo "Error:                    build-xkit-lib:   FAILED TO CREATE        src/lib/x-kit/xkit.lib.frozen"
    exit 1
fi

exit 0;
