#!/bin/sh
#
# build script for bin/nowhere
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the executable bin/nowhere.
#
# options:
#   -o image		-- specify the name of the heap image, "nowhere"
#			   is the default.

CMD=$0

NOWHERE="nowhere"
HEAP_IMAGE=""
HERE=`pwd`
cd ../../../../../../..
SEVEN_UP=`pwd`
cd $HERE
BIN=${INSTALL_DIR:-$SEVEN_UP}/bin
MAKELIB=$BIN/build-an-executable-mythryl-heap-image

echo
echo '--------------------------------------------'
echo "                       build-nowhere-app:   Starting."

#
# Process command-line options:
while [ "$#" != "0" ] ; do
    arg=$1
    shift
    case $arg in
	-o)
	    if [ "$#" = "0" ]; then
		echo "                       build-nowhere-app:   Must supply image name for -o option"
		exit 1
	    fi
	    HEAP_IMAGE=$1; shift
	    ;;
	*)
	    echo "                       build-nowhere-app:   Invalid argument: $arg"
	    exit 1
	    ;;
    esac
done

if [ "$HEAP_IMAGE" = "" ]; then
    HEAP_IMAGE="$NOWHERE"
fi

echo "                       build-nowhere-app:   Doing:                  $MAKELIB nowhere.lib no_where::main $HEAP_IMAGE"
$MAKELIB nowhere.lib no_where::main $HEAP_IMAGE



if [ -f "$HEAP_IMAGE" ]; then

    echo "                       build-nowhere-app:   $HEAP_IMAGE created."

    if [ -f "$BIN/$NOWHERE" ]; then
        echo "                       build-nowhere-app:   Removing $BIN/$NOWHERE"
        rm $BIN/$NOWHERE
    fi

    echo "                       build-nowhere-app:   Installing $HEAP_IMAGE as $BIN/$NOWHERE"
    cp "$HEAP_IMAGE" "$BIN/$NOWHERE"
    chmod +x "$BIN/$NOWHERE"
    rm "$HEAP_IMAGE"

else
    echo "                       build-nowhere-app:   $HEAP_IMAGE not created, aborting."
    exit 1
fi



echo "                       build-nowhere-app:   Done."
echo
echo
echo


exit 0