#!/bin/sh
# 
# list all known fonts -- make sure all descriptions have at least 8 fields
# (shorter descriptions may match more patterns than you would like)
# in particular, exclude font aliases like 9x13 and the like.
exec xlsfonts -fn '*-*-*-*-*-*-*-*'
