#!/bin/sh
#
# This script supports the modern habit of installing a package via
#
#     ./Configure
#     make
#     make check
#     make install
#
# If you're a maintainer looking for Configure.in, Makefile.in, aclocal.m4 &tc,
# you'll find them tucked away in src/runtime/ to reduce root-directory clutter.
#
make configure

