src/lib/std/src/io/threadkit-winix-base-file-io-driver-for-posix-g.pkg:  For clarity and consistency renamed read_vect_mailop -> read_vector_mailop, read_arr_mailop -> read_rw_vector_mailop, write_vec_mailop -> write_vector_mailop, write_arr_mailop.'

    src/lib/std/threadkit-winix.pkg
    src/lib/std/src/threadkit/threadkit-process-result.pkg
    src/lib/std/src/threadkit/posix/threadkit-winix-io.pkg
    src/lib/std/src/socket/threadkit-pre-socket.pkg
    src/lib/std/src/socket/threadkit-socket.pkg
    src/lib/std/src/socket/threadkit-plain-socket.pkg
    src/lib/std/src/socket/threadkit-internet-socket.pkg
    src/lib/std/src/socket/threadkit-unix-domain-socket.pkg
    src/lib/std/src/io/threadkit-winix-base-file-io-driver-for-posix-g.pkg
    src/lib/std/src/io/threadkit-winix-data-file-for-os-g.pkg
    src/lib/std/src/io/threadkit-winix-base-data-file-io-driver-for-posix.pkg
    src/lib/std/src/io/threadkit-io-cleanup-at-shutdown.pkg
    src/lib/std/src/io/threadkit-winix-base-text-file-io-driver-for-posix.pkg
    src/lib/std/src/io/threadkit-winix-mailslot-io-g.pkg
    src/lib/std/src/io/threadkit-winix-text-file-for-os-g.pkg
    src/lib/std/src/posix/threadkit-winix-data-file-io-driver-for-posix.pkg
    src/lib/std/src/posix/threadkit-winix-process.pkg
    src/lib/std/src/posix/threadkit-file.pkg
    src/lib/std/src/posix/threadkit-winix-data-file-for-posix.pkg
    src/lib/std/src/posix/threadkit-spawn.pkg
    src/lib/std/src/posix/threadkit-winix-text-file-for-posix.pkg
    src/lib/std/src/posix/threadkit-winix-text-file-io-driver-for-posix.pkg
    src/lib/std/src/posix/threadkit-data-file.pkg
    src/lib/src/lib/thread-kit/src/core-thread-kit/threadkit.pkg
    src/lib/src/lib/thread-kit/src/core-thread-kit/threadkit-version.pkg
    src/lib/src/lib/thread-kit/src/core-thread-kit/threadkit-queue.pkg
    src/lib/src/lib/thread-kit/src/core-thread-kit/threadkit-debug.pkg
    src/lib/src/lib/thread-kit/src/core-thread-kit/threadkit-io-manager.pkg
    src/lib/src/lib/thread-kit/src/core-thread-kit/threadkit-unit-test.pkg
    src/lib/src/lib/thread-kit/src/core-thread-kit/threadkit-startup-and-shutdown-hooks.pkg
    src/lib/src/lib/thread-kit/src/win32/threadkit-winix-text-file-io-driver-for-win32.pkg
    src/lib/src/lib/thread-kit/src/win32/threadkit-winix-text-file-for-win32.pkg
    src/lib/src/lib/thread-kit/src/win32/threadkit-winix-data-file-io-driver-for-win32.pkg
    src/lib/src/lib/thread-kit/src/lib/threadkit-uncaught-exception-reporting.pkg
    src/lib/src/lib/thread-kit/src/posix/threadkit-driver-for-posix.pkg
    src/lib/src/lib/thread-kit/src/glue/threadkit-export-function-g.pkg
    src/lib/src/threadkit-quickstring.pkg
