# Makefile.make6
#



LIBRARY_EXPORTS

	generic  prettyprint_buffer_g
	generic  prettyprint_stream_g
	generic  prettyprint_debug_g

	pkg simple_text_io_device
	pkg html_device

	pkg html
	pkg prettyprint_html_tree



LIBRARY_COMPONENTS

	$ROOT/src/lib/std/stdlib.make6
	$ROOT/src/lib/html/html-lib.make6
	$ROOT/src/lib/prettyprint/Prettyprint.make6


# COPYRIGHT (c) 1997 Bell Labs, Lucent Technologies.
# Subsequent changes by Jeff Prothero Copyright (c) 2010,
# released under Gnu Public Licence version 3.
