#!/usr/bin/perl -w
use strict;

# 2009-10-16 CrT:
#     I have 
#
#         AC_CHECK_HEADERS([gtk-2.0/gtk/gtk.h])
#         AC_CHECK_HEADERS([gtk/gtk.h])
#
#     in Configure.in here but config.h winds up with
#
#         HAVE_GTK_2_0_GTK_GTK_H 0
#         HAVE_GTK_GTK_H 0
#
#     even though the former exists on my system.
#
#     This appears to be a problem with gtk.h being
#     full of includes which don't come up properly
#     if one hasn't done `pkg-config --cflags gtk+-2.0` `pkg-config --libs gtk+-2.0`
#     which the autoconf logic does not do.
#
#     The following is a quick and dirty hack
#     to resolve this problem.
#
#     If you know of a better way, post or email. :-)



my $have_gtk_2_0_gtk_gtk_h = "0";

if (-f "/usr/include/gtk-2.0/gtk/gtk.h") {
    $have_gtk_2_0_gtk_gtk_h = "1";
}



my $have_gtk_gtk_h = "0";

if (-d "/usr/include/gtk/gtk.h") {
    $have_gtk_gtk_h = "1";
}



my $input_file  = "src/runtime/config.h";
my $output_file = "${input_file}.soon";
my $backup_file = "${input_file}~";

open IN,    "$input_file" || die "Cannot read $input_file!\n";
open OUT, ">$output_file" || die "Cannot write $output_file!\n";

while (my $line = <IN>) {
    if    ($line =~ /^#define HAVE_GTK_2_0_GTK_GTK_H /) { $line = "#define HAVE_GTK_2_0_GTK_GTK_H $have_gtk_2_0_gtk_gtk_h\n"; }
    elsif ($line =~ /^#define HAVE_GTK_GTK_H /)         { $line = "#define HAVE_GTK_GTK_H $have_gtk_gtk_h\n"; }
    print OUT $line;
}

close OUT || die "Couldn't close $output_file?!";
close IN;

rename( $input_file,  $backup_file );
rename( $output_file, $input_file  );

print "               src/runtime/check-for-gtk:   Patched into src/runtime/config.h:\n";
print "                                                                    #define HAVE_GTK_2_0_GTK_GTK_H $have_gtk_2_0_gtk_gtk_h\n";
print "                                                                    #define HAVE_GTK_GTK_H $have_gtk_gtk_h\n";

exit 0;

