# win32 specific, only mem-vmem currently supported.
#
# The makefile for the memory management library.  This gets recursively
# invoked with the OBJS variable set to the appropriate value.
#

MAKE =		nmake
AR =		lib
ARFLAGS =	
RANLIB =	lib

VERSION =	v-dummy

LIB =		libmythryl-ram.lib

MMAP_OBJS =	get-multipage-ram-region-from-mmap.obj

MACH_OBJS =	get-multipage-ram-region-from-mach.obj

BRK_OBJS =	mem-brk.obj malloc.obj

SIMPLE_OBJS = 	get-multipage-ram-region-from-win32.obj

$(LIB) :	$(VERSION) $(OBJS)
	$(AR) $(ARFLAGS) /out:$(LIB) $(OBJS)
	$(RANLIB) /out:$(LIB)

$(VERSION) :
	echo "$(VERSION)" > $(VERSION)

get-multipage-ram-region-from-mmap.obj get-multipage-ram-region-from-mach.obj mem-brk.obj get-multipage-ram-region-from-win32.obj:	get-multipage-ram-region-from-os-stuff.c

DEPENDENTS = ..\include\runtime-base.h ..\include\system-dependent-unix-stuff.h ..\h\sibid.h

get-multipage-ram-region-from-mmap.obj : get-multipage-ram-region-from-mmap.c $(DEPENDENTS)
	$(CC) $(CFLAGS) $(DEFS) $(INCLUDES) /c get-multipage-ram-region-from-mmap.c

get-multipage-ram-region-from-mach.obj : get-multipage-ram-region-from-mach.c $(DEPENDENTS)
	$(CC) $(CFLAGS) $(DEFS) $(INCLUDES) /c get-multipage-ram-region-from-mach.c

mem-brk.obj : mem-brk.c $(DEPENDENTS)
	$(CC) $(CFLAGS) $(DEFS) $(INCLUDES) /c mem-brk.c

malloc.obj : malloc.c $(DEPENDENTS)
	$(CC) $(CFLAGS) $(DEFS) $(INCLUDES) /c malloc.c

get-multipage-ram-region-from-win32.obj : get-multipage-ram-region-from-win32.c get-multipage-ram-region-from-os-stuff.c ..\include\runtime-base.h ..\include\system-dependent-stuff.h ..\include\get-multipage-ram-region-from-os.h
	$(CC) $(CFLAGS) $(DEFS) $(INCLUDES) /c get-multipage-ram-region-from-win32.c

clean :
	del /F /Q v-* *.obj *.pdb $(LIB)

