// cfun-list.h
//
//
// This file lists the directory library of C functions that are callable from Mythryl.

// This table ultimately gets searched by
//
//     get_mythryl_callable_c_function() 	in   src/c/lib/mythryl-callable-c-libraries.c


#ifndef CLIB_NAME
#define CLIB_NAME	"sdl"
#define CLIB_VERSION	"1.0"
#define CLIB_DATE	"February 13, 2008"
#endif

CFUNC("init","init",	_lib7_Sdl_sdl_init,		"Void -> Void")

CFUNC("callback_queue_is_empty","callback_queue_is_empty",	   _lib7_Sdl_callback_queue_is_empty,		"Void -> Bool")
CFUNC("number_of_queued_callbacks","number_of_queued_callbacks",	   _lib7_Sdl_number_of_queued_callbacks,	"Void -> Int")
CFUNC("type_of_next_queued_callback","type_of_next_queued_callback",	   _lib7_Sdl_type_of_next_queued_callback,	"Void -> Int")
CFUNC("get_queued_void_callback","get_queued_void_callback",	   _lib7_Sdl_get_queued_void_callback,		"Void -> Int")
CFUNC("get_queued_bool_callback","get_queued_bool_callback",	   _lib7_Sdl_get_queued_bool_callback,		"Void -> (Int, Bool)")
CFUNC("get_queued_float_callback","get_queued_float_callback",	   _lib7_Sdl_get_queued_float_callback,		"Void -> (Int, Float)")
CFUNC("get_queued_button_press_callback","get_queued_button_press_callback",  _lib7_Sdl_get_queued_button_press_callback,	"Void -> (Int, Int, Int, Float, Float, Int, Int)")  // Void -> (callback_number, widget_id, button, x, y, time, modifiers)
CFUNC("get_queued_key_press_callback","get_queued_key_press_callback",     _lib7_Sdl_get_queued_key_press_callback,	"Void -> (Int, Int, Int, Int, Int)")                // Void -> (callback_number, key, keycode, time, modifiers)
CFUNC("get_queued_motion_notify_callback","get_queued_motion_notify_callback", _lib7_Sdl_get_queued_motion_notify_callback,	"Void -> (Int, Int, Int, Float, Float, Int, Bool)") // Void -> (callback_number, widget_id, time, x, y, modifiers, is_hint)
CFUNC("get_queued_expose_callback","get_queued_expose_callback",        _lib7_Sdl_get_queued_expose_callback,	"Void -> (Int, Int, Int, Int, Int, Int, Int)")      // Void -> (callback_number, widget, count, area_x, area_y, area_wide, area_high)
CFUNC("get_queued_configure_callback","get_queued_configure_callback",     _lib7_Sdl_get_queued_configure_callback,	"Void -> (Int, Int, Int, Int, Int, Int)")           // Void -> (callback_number, widget, x,    y,    wide, high)

CFUNC("get_widget_allocation","get_widget_allocation",             _lib7_Sdl_get_widget_allocation,		"Int -> (Int, Int, Int, Int)")                      // Widget -> (x,    y,    wide, high)
CFUNC("make_dialog","make_dialog",                       _lib7_Sdl_make_dialog,			"Void -> (Int, Int, Int)")                          // Void   -> (dialog, vbox, action-area)
CFUNC("unref_object","unref_object",                      _lib7_Sdl_unref_object,			"Int -> Void")                                      // Widget -> Void
CFUNC("run_eventloop_once","run_eventloop_once",                _lib7_Sdl_run_eventloop_once,		"Bool -> Bool")                                     // Bool -> Bool



/* Do not edit this or following lines -- they are autogenerated by make-sdl-glue. */
/* Do not edit this or preceding lines -- they are autogenerated by make-sdl-glue. */



// COPYRIGHT (c) 1995 AT&T Bell Laboratories.
// Subsequent changes by Jeff Prothero Copyright (c) 2010-2012,
// released under Gnu Public Licence version 3.

