#!/bin/sh

this=$0
here=`pwd`
cd ../..
twoup=`pwd`
cd $here

MYTHRYLD=$twoup/bin/mythryld

# -Clowcode.asm-show-cellset=true -Clowcode.asm-show-region=true -Clowcode.asm-show-cutsto=true -Clowcode.ra-verbose=true -Clowcode.dump-cfg-before-ra=true -Clowcode.dump-cfg-after-all-ra=true -Clowcode.view-outline=true -Clowcode.dump-cfg-after-loop-probabilities=true -Clowcode.dump-cfg-after-complete-probs=true -Clowcode.dump-cfg-after-frequencies=true -Clowcode.dump-cfg-after-placement=true -Clowcode.dump-initial-cfg=true -Ccontrol.printRawSyntaxTree=true -Ccontrol.printDeepSyntaxTree=true -Clowcode.dump-cfg-after-all-ra=true -Chighcode.print-phases=true -Ccg.verbose=true -Chighcode.print=true -Chighcode.print-phases=true <<EOF

$MYTHRYLD -Cprint.length=30 -Cprint.signatures=30 -Cprint.depth=50  -Ccontrol.printRawSyntaxTree=true <<EOF
    datatype boojum = SILENTLY | VANISH of int | AWAY of boojum ref
    fun add3 (a,b,c) = a+b+c
    fun addp {a,b,c} = a+b+c
    fun test i = TextIO.output i
    fun factorial 0 = 1
      | factorial n = n * factorial (n-1)
    fun case_example (i) = case i of 1 => 101 | 2 => 202
    fun let_example (j) = let val k = 2 * j in k end
    fun exception_example (f) = let exception myException of int in f () handle myException _ => () end
    val _ = 12
EOF

exit 0
