#!/usr/bin/perl -w
use strict;

# 2007-05-01 CrT: A quick hack to find files which aren't being compiled
#                 by the main makefile.  It depends on the fact that at
#                 the moment the compiler is tweaked to generate a
#                 foo.EDIT_REQUESTS file for each file 'foo' it compiles:

open (FD, 'find . -type f -name \'*EDIT_REQUESTS\'|') or die "Couldn't read *pkg.EDIT_REQUESTS: $!\n";

my %known = ();

while (my $file = <FD>) {
    chomp $file;
    if ($file =~ /^(.*).EDIT_REQUESTS$/) {
        my $basename = $1;
#        print "$file -> $basename\n";
        ++ $known{ $basename };
    }
}
close FD;

open (FD, 'find . -type f -name \'*.api\'|') or die "Couldn't read *.api: $!\n";
while (my $file = <FD>) {
    chomp $file;
    if (not defined $known{ $file }) {
        print "Maverick: $file\n";
    }
}
close FD;


open (FD, 'find . -type f -name \'*.pkg\'|') or die "Couldn't read *.pkg: $!\n";
while (my $file = <FD>) {
    chomp $file;
    if (not defined $known{ $file }) {
        print "Maverick: $file\n";
    }
}
close FD;


exit(0);
