#!/usr/bin/perl -w
use strict;

# Simple script to update the the contents of the
# Mythryl mainline on the github.com repository
# with the contents of the latest
#
#     ../mythryl7*-dist-*tar.bz2
#
# file.  `ls -lart ../mythryl7*-dist-*tar.bz2`  will usually show something like
#
#    -rw-r--r-- 1 cynbe cynbe 12929931 2009-03-04 20:49 ../mythryl7.110.58-dist-2009-03-04-20.49.26.tar.bz2
#    -rw-r--r-- 1 cynbe cynbe 12963550 2009-03-05 22:12 ../mythryl7.110.58-dist-2009-03-05-22.12.29.tar.bz2
#    -rw-r--r-- 1 cynbe cynbe 12946364 2009-03-06 13:27 ../mythryl7.110.58-dist-2009-03-06-13.27.33.tar.bz2
#    -rw-r--r-- 1 cynbe cynbe 12941865 2009-03-06 23:15 ../mythryl7.110.58-dist-2009-03-06-23.15.19.tar.bz2
#    -rw-r--r-- 1 cynbe cynbe 12943205 2009-03-07 22:48 ../mythryl7.110.58-dist-2009-03-07-22.48.25.tar.bz2
#    -rw-r--r-- 1 cynbe cynbe 12930466 2009-03-09 07:24 ../mythryl7.110.58-dist-2009-03-09-07.23.55.tar.bz2
#    -rw-r--r-- 1 cynbe cynbe 12967065 2009-03-12 03:38 ../mythryl7.110.58-dist-2009-03-12-03.37.49.tar.bz2
#    -rw-r--r-- 1 cynbe cynbe 12942931 2009-03-12 18:23 ../mythryl7.110.58-dist-2009-03-12-18.23.13.tar.bz2
#    -rw-r--r-- 1 cynbe cynbe 12921212 2009-03-15 21:47 ../mythryl7.110.58-dist-2009-03-15-21.46.47.tar.bz2
#    -rw-r--r-- 1 cynbe cynbe 12934484 2009-03-18 05:27 ../mythryl7.110.58-dist-2009-03-18-05.26.46.tar.bz2
#    -rw-r--r-- 1 cynbe cynbe 13088854 2009-04-03 12:35 ../mythryl7.110.58-dist-2009-04-03-12.35.06.tar.bz2
#    -rw-r--r-- 1 cynbe cynbe 13097425 2009-06-05 00:57 ../mythryl7.110.58-dist-2009-06-05-00.56.59.tar.bz2
#    -rw-r--r-- 1 cynbe cynbe 13194452 2009-08-19 14:02 ../mythryl7.110.58-dist-2009-08-19-14.01.49.tar.bz2
#
# It is presumed that a previous run of our matching
# script 'git-get' created a
#
#     ../git/my
#
# copy of the current repository contents.
#
#  -> Many thanks to Andrea Dallera for setting up the
#     Mythryl git archive there and showing me how to use it!
#
# 2009-08-23 CrT: Created.

my $DIR = "mythryl7.110.58";

if ($#ARGV != 0) {
    print "usage:  sh/git-put 'comment for this check-in'\n";
    exit(1);
}

my $checkin_comment = $ARGV[0];

if (! -d "../git/$DIR") {
    print "../git/$DIR does not exist -- did you run 'sh/git-get'?\n";
    exit(1);
}

my $last_line = "";

# List all our Mythryl -dist- tarballs in
# reverse chronological order.  The last
# one will be the one we want:
#
open IN, "ls -lart ../mythryl*-dist-*tar.bz2 |";
while (<IN>) {
    chomp;
    $last_line = $_;
}

my $distfile = "";
my $version  = "";
if ($last_line =~ m|(\.\./mythryl.*-dist-(.*)\.tar.bz2)$|) {
    $distfile = $1;
    $version  = $2;
} else {
    print "Did not find a ../mythryl*-dist-*tar.bz2 file to post!\n";
    exit(1);
}

# Prepend a line to change-log:
#
`echo "$version: $checkin_comment" > change-log1`;
`mv change-log change-log2`;
`cat change-log1 change-log2 >change-log`;
`rm change-log1`;
`rm change-log2`;

print "Posting file $distfile to github as '$version: $checkin_comment'...\n";


chdir "../git";

# Originally I was just doing
#     system("tar -xjf $distfile");		# Unpack new distribution over git directory.
# here, but that results in files which
# have been renamed in or deleted from
# my primary archive persisting in the
# github archive, so now we nuke and
# restore everything but .git/ and .gitignore
# on each cycle:
system("mv $DIR/.git .");
system("mv $DIR/.gitignore .");
system("rm -rf $DIR");
system("mkdir $DIR");
system("mv .git $DIR");
system("mv .gitignore $DIR");
#
system("tar -xjf $distfile");		# Unpack new distribution over git directory.

chdir "$DIR";

system("git add .");
system("git tag -am \"$checkin_comment\" \"$version\"");
system("git commit -am \"$version: $checkin_comment\"");
system("git push");

print "Done pushing '$version: $checkin_comment' to github.\n";

exit(0);

