#!/usr/bin/perl -w
use strict;

# Simple script to update the the contents of the
# Mythryl mainline on the github.com repository
# with the contents of this directory.
#
#  -> Many thanks to Andrea Dallera for setting up the
#     Mythryl git archive there and showing me how to use it!
#
# 2009-08-23 CrT: Created.

# See also:  ./log-change

my $DIR = "mythryl7.110.58";

if ($#ARGV != 0) {
    print "usage:  sh/git-put 'comment for this check-in'\n";
    exit(1);
}

my $checkin_comment = $ARGV[0];

my $last_line = "";

# Construct a date+time stamp as a checkin version number:
my $version = `date +"%Y-%m-%d-%T"`;   chomp( $version );
$version =~ tr/:/./;

# Prepend a line to change-history:
#
`echo "$version: $checkin_comment" > change-history1`;
`mv change-history change-history2`;
`cat change-history1 change-history2 >change-history`;
`rm change-history1`;
`rm change-history2`;

print "Posting to github:  '$version: $checkin_comment'...\n";

system("git add .");
system("git tag -am \"$checkin_comment\" \"$version\"");
system("git commit -am \"$version: $checkin_comment\"");
system("git push");

print "Done pushing '$version: $checkin_comment' to github.\n";

exit(0);

