#!/usr/bin/perl -w
use strict;

# This script was produced essentially by taking ./git-put
# and removing all the git stuff, leaving just the update
# to ../change-log.  However, we don't require that the
# unneeded *-dist-* file exist (e.g. mythryl7.110.58-dist-2010-09-30-12.40.12.tar.bz2)
# instead looking for just the base  mythryl7.110.58-2010-09-30-12.40.12.tar.bz2 file.
#
# 2010-10-14 CrT: Created.

my $DIR = "mythryl7.110.58";

if ($#ARGV != 0) {
    print "usage:  sh/log-change 'comment for this check-in'\n";
    exit(1);
}

my $checkin_comment = $ARGV[0];

my $last_line = "";

# List all our Mythryl -dist- tarballs in
# reverse chronological order.  The last
# one will be the one we want:
#
open IN, "ls -lart ../mythryl7.110.58-2*tbz |";
while (<IN>) {
    chomp;
    $last_line = $_;
}

my $tarfile = "";
my $version  = "";
if ($last_line =~ m|(\.\./mythryl7.110.58-(.*)\.tbz)$|) {
    $tarfile = $1;
    $version = $2;
} else {
    print "Did not find a ../mythryl7.110.58-*tbz file to changelog!\n";
    exit(1);
}

# Prepend a line to change-log:
#
`echo "$version: $checkin_comment" > change-log1`;
`mv change-log change-log2`;
`cat change-log1 change-log2 >change-log`;
`rm change-log1`;
`rm change-log2`;

exit(0);

