#!/usr/bin/perl -w
use strict;

# 2007-07-24 CrT: A quick hack to find files which have a .EDIT_REQUESTS
#                 but not a .SEEN flag, meaning that they get compiled,
#                 but aren't being processed by sh/update-commments.

# Usage:
# (1) Uncomment the two lines marked "# lost-sheep hack." in sh/update-comments.
# (2) Do "make init", "make self", "make comments", "sh/lost-sheep".

# When last used, the result looks like so:
#
#   cynbe@chee mythryl7.110.58/mythryl7.110.58% sh/lost-sheep
#   ./src/lib/core/init/xcore.pkg.EDIT_REQUESTS exists, but not ./src/lib/core/init/xcore.pkg.SEEN
#   ./src/lib/core/init/math-built-in-x86.pkg.EDIT_REQUESTS exists, but not ./src/lib/core/init/math-built-in-x86.pkg.SEEN
#   ./src/lib/core/init/pervasive.pkg.EDIT_REQUESTS exists, but not ./src/lib/core/init/pervasive.pkg.SEEN
#   ./src/lib/core/init/rawmem.pkg.EDIT_REQUESTS exists, but not ./src/lib/core/init/rawmem.pkg.SEEN
#   ./src/lib/core/internal/versiontool.pkg.EDIT_REQUESTS exists, but not ./src/lib/core/internal/versiontool.pkg.SEEN
#   ./sh/build.d/build.pkg.EDIT_REQUESTS exists, but not ./sh/build.d/build.pkg.SEEN
#   ./sh/build.d/unix-build.pkg.EDIT_REQUESTS exists, but not ./sh/build.d/unix-build.pkg.SEEN
#
# Those are all special cases better handled by hand-commenting
# than by tweaking sh/update-comments.

open (FD, 'find . -type f -name \'*.pkg.EDIT_REQUESTS\'|') or die "Couldn't read *pkg.EDIT_REQUESTS: $!\n";

while (my $file = <FD>) {
    chomp $file;
    if ($file =~ /^(.*).EDIT_REQUESTS$/) {
        my $basename = $1;
        my $seen = $basename . ".SEEN";
        if (! -r $seen) {
            print "$file exists, but not $seen\n";
        }
    }
}
close FD;

exit(0);
