#!/bin/sh

# Re/compile all source code that
# goes into the Mythryl compiler.
											# mythryl_compiler_compiler_for_this_platform	is set by   src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-this-platform.lib
											#                                               to one of:
											# mythryl_compiler_compiler_for_intel32_posix	is from   src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-intel32-posix.pkg
											# mythryl_compiler_compiler_for_intel32_win32	is from   src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-intel32-win32.pkg
											# mythryl_compiler_compiler_for_pwrpc32_macos	is from   src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-pwrpc32-macos.pkg
											# mythryl_compiler_compiler_for_pwrpc32_posix	is from   src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-pwrpc32-posix.pkg
											# mythryl_compiler_compiler_for_sparc32_posix	is from   src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-sparc32-posix.pkg
								#                                                                                        ...
# Recompile 'mythryl_compiler_compiler_for_this_Platform' (if necessary)
# and then run it:
#

bin/mythryld  src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-this-platform.lib  <<EOF
    mythryl_compiler_compiler_for_this_platform::make_mythryl_compiler ();
EOF

exit 0

