#!/bin/sh

								# make_compiler		is from   src/app/make7/make-compiler/make-compiler-g.pkg
# Recompile 'make_compiler' (if necessary)
# and then run it:
#
bin/mythryld src/lib/core/make-compiler/current.make6 <<EOF
    make7::make ();
EOF

exit 0

