#!/bin/sh

# For intel32 we synthesize the sourcefiles
#
#     src/lib/compiler/back/low/intel32/code/machcode-intel32.codemade.api
#     src/lib/compiler/back/low/intel32/code/machcode-intel32-g.codemade.pkg
#     src/lib/compiler/back/low/intel32/code/registerkinds-intel32.codemade.pkg
#     src/lib/compiler/back/low/intel32/emit/translate-machcode-to-asmcode-intel32-g.codemade.pkg
#
# from the more abstract Architecture Description File
#
#    src/lib/compiler/back/low/intel32/intel32.architecture-description
#
# See comments in latter file for more detail.
#
# Our job in this file is to do this code synthesis.
#
# (The other un/supported architectures are supposed to have
# similar arrangements, but that is not currently working.)
#
# We are normally invoked as needed by the
#
#     : shell (source: ../intel32/one_word_int.architecture-description options:shared sh/make-sourcecode-for-backend-intel32)
#
# makelib qualifiers in
#
#     src/lib/compiler/back/low/intel32/backend-intel32.lib
#
# but that makelib functionality is broken at present,
# hence commented out -- we just invoke this script
# manually whenever we change intel32.architecture-description
#
# When makelib gets fixed, the
#
#     @find . -type f -name '*.codemade.*' -print | xargs rm -f;
#                
# line in the main Makefile should be uncommented.
#
# In the meantime, this script gets run every development cycle by the
#     backends:
# target in Makefile, just to guard against creeping bitrot.
#
#                     -- 2011-05-18 CrT 


bin/mythryld  src/lib/compiler/back/low/tools/arch/make-sourcecode-for-backend-packages.lib  <<EOF
    #
    package intel32 = make_sourcecode_for_backend_intel32;
    intel32::make_sourcecode_for_backend_intel32  "src/lib/compiler/back/low/intel32/intel32.architecture-description";
EOF

exit 0

