#!/bin/sh

# This script is invoked directly by Makefile's "compiler-executable:"
# rule, as the second half of responding to a toplevel "make compiler".
#
# We build our all-in-one "executable" (heap image)
# 
#     bin/mythryld
#
# which combines our compiler, linker, make support and
# interactive system all in one big happy binary -- once
# we have it up and running we have a usable Mythryl install.
#
if [ -r mythryld ]; then
    echo "             sh/make-compiler-executable:   Removing old 'mythryld' file."
    rm mythryld
fi

# export CM_DIR_ARC="tmp7"

# bin/mythryl-ld is a small wrapper script around bin/mythryl-runtime-intel32.
# bin/mythryl-runtime-intel32, Mythryl's C-coded runtime layer, has
# special bootstrap functionality to build the initial
# compiler heap image by reading in a designated set of
# .compiled files in a designated order and then saving the
# resulting heap image to disk:
#
if bin/mythryl-ld --runtime-compiledfiles-to-load=COMPILED_FILES_TO_LOAD --runtime-gc-gen0-bufsize=256k
then

    if [ -r mythryld ]; then

        chmod +x mythryld
	echo "             sh/make-compiler-executable:   Success: 'mythryld' executable generated."

        if [ -r bin/mythryld ]; then
	    echo "             sh/make-compiler-executable:   Saving previous  bin/mythryld  as  bin/mythryld.previous."
	    mv bin/mythryld bin/mythryld.previous
        fi

	# If this is our first compile, also save it as bin/mythryld-bare.
	# We need this when doing "sh/glue drop foo", because we cannot run
	# the standard bin/mythryld on a downsized runtime lacking support
	# for some of  bin/mythryld's libraries:
	#
	if [ ! -f bin/mythryld-bare ]; then
	    echo "             sh/make-compiler-executable:   Saving mythryld  as  bin/mythryld-bare."
	    cp mythryld     bin/mythryld-bare
	fi

	echo "             sh/make-compiler-executable:   Installing new   bin/mythryld  executable (and 'my' symlink to it)."

	mv mythryld     bin/mythryld

        if [ -L bin/my ]; then
            rm bin/my
        fi
	if [ ! -e bin/my ]; then
	    (cd bin;  ln -s mythryld my)
	fi

	echo     "             sh/make-compiler-executable:   `ls -l bin/my`"
	echo     "             sh/make-compiler-executable:   `ls -l bin/mythryld-bootstrap`"
	echo     "             sh/make-compiler-executable:   `ls -l bin/mythryld-bare`"

	if [ -f bin/mythryld.previous ] ; then
	    echo "             sh/make-compiler-executable:   `ls -l bin/mythryld.previous`"
	fi

	echo     "             sh/make-compiler-executable:   `ls -l bin/mythryld`"
	echo     ""
	echo     ""
	echo     "             To run Mythryl interactively do:  bin/my"
	echo     ""

    else
	echo     "             sh/make-compiler-executable:   No mythryld executable generated."
    fi
else
    echo "             sh/make-compiler-executable:   Compiler link failed, no mythryld executable"
fi

