#!/bin/sh

# For pwrpc32 we synthesize the sourcefiles
#
#     src/lib/compiler/back/low/pwrpc32/code/machcode-pwrpc32.codemade.api
#     src/lib/compiler/back/low/pwrpc32/code/machcode-pwrpc32-g.codemade.pkg
#     src/lib/compiler/back/low/pwrpc32/code/registerkinds-pwrpc32.codemade.pkg
#     src/lib/compiler/back/low/pwrpc32/emit/translate-machcode-to-asmcode-pwrpc32-g.codemade.pkg
#     src/lib/compiler/back/low/pwrpc32/emit/translate-machcode-to-execode-pwrpc32-g.codemade.pkg
#
# from the more abstract Architecture Description File
#
#    src/lib/compiler/back/low/pwrpc32/pwrpc32.architecture-description
#
# See comments in latter file for more detail.
#
# Our job in this file is to do this code synthesis.
#
# We are normally invoked as needed by the
#
#     : shell (source: ../pwrpc32/pwrpc32.architecture-description options:shared sh/make-sourcecode-for-backend-pwrpc32)
#
# makelib qualifiers in
#
#     src/lib/compiler/back/low/pwrpc32/backend-pwrpc32.lib
#
# but that makelib functionality is broken at present,
# hence commented out -- we just invoke this script
# manually whenever we change pwrpc32.architecture-description
#
# When makelib gets fixed, the
#
#     @find . -type f -name '*.codemade.*' -print | xargs rm -f;
#                
# line in the main Makefile should be uncommented.
#
#                     -- 2011-05-18 CrT 

bin/mythryld  src/lib/compiler/back/low/tools/arch/make-sourcecode-for-backend-packages.lib  <<EOF
    #
    package pwrpc32 = make_sourcecode_for_backend_pwrpc32;
    pwrpc32::make_sourcecode_for_backend_pwrpc32  "src/lib/compiler/back/low/pwrpc32/pwrpc32.architecture-description";
EOF

exit 0

