#!/bin/sh

# UN-Install mythryl globally (/usr/bin etc).
# You'll need to be root to run this, most likely.

# Created 2007-03-15 CrT under LGPL.

if [ -x /usr/bin/mythryl-runtime-intel32 ]; then
    rm  /usr/bin/mythryl-runtime-intel32

    if [ -x /usr/bin/mythryl-runtime-intel32 ]; then
	echo "Couldn't rm /usr/bin/mythryl-runtime-intel32 -- you may need to su to root to uninstall."
	exit 1
    else
	echo "/usr/bin/mythryl-runtime-intel32 successfully removed."
    fi
fi

if [ -x /usr/bin/mythryl-ld ]; then
    rm  /usr/bin/mythryl-ld

    if [ -x /usr/bin/mythryl-ld ]; then
	echo "Couldn't rm /usr/bin/mythryl-ld -- you may need to su to root to uninstall."
	exit 1
    else
	echo "/usr/bin/mythryl-ld successfully removed."
    fi
fi

if [ -x /usr/bin/mythryl ]; then
    rm  /usr/bin/mythryl

    if [ -x /usr/bin/mythryl ]; then
	echo "Couldn't rm /usr/bin/mythryl -- you may need to su to root to uninstall."
	exit 1
    else
	echo "/usr/bin/mythryl successfully removed."
    fi
fi

if [ -x /usr/bin/mythryld ]; then
    rm  /usr/bin/mythryld

    if [ -x /usr/bin/mythryld ]; then
	echo "Couldn't rm /usr/bin/mythryld -- you may need to su to root to uninstall."
	exit 1
    else
	echo "/usr/bin/mythryld successfully removed."
    fi
fi

if [ -x /usr/bin/my ]; then
    rm  /usr/bin/my

    if [ -x /usr/bin/my ]; then
	echo "Couldn't rm /usr/bin/my -- you may need to su to root to uninstall."
	exit 1
    else
	echo "/usr/bin/my successfully removed."
    fi
fi



####################################################################################
# Do not edit this or following lines --- they are autobuilt.  (patchname="remove")

if [ -x /usr/bin/mythryl-qqq-library-in-c-subprocess ]; then
    rm  /usr/bin/mythryl-qqq-library-in-c-subprocess

    if [ -x /usr/bin/mythryl-qqq-library-in-c-subprocess ]; then
	echo "Couldn't rm /usr/bin/mythryl-qqq-library-in-c-subprocess -- you may need to su to root to uninstall."
	exit 1
    else
	echo "/usr/bin/mythryl-qqq-library-in-c-subprocess successfully removed."
    fi
fi


if [ -x /usr/bin/mythryl-opengl-library-in-c-subprocess ]; then
    rm  /usr/bin/mythryl-opengl-library-in-c-subprocess

    if [ -x /usr/bin/mythryl-opengl-library-in-c-subprocess ]; then
	echo "Couldn't rm /usr/bin/mythryl-opengl-library-in-c-subprocess -- you may need to su to root to uninstall."
	exit 1
    else
	echo "/usr/bin/mythryl-opengl-library-in-c-subprocess successfully removed."
    fi
fi


if [ -x /usr/bin/mythryl-opencv-library-in-c-subprocess ]; then
    rm  /usr/bin/mythryl-opencv-library-in-c-subprocess

    if [ -x /usr/bin/mythryl-opencv-library-in-c-subprocess ]; then
	echo "Couldn't rm /usr/bin/mythryl-opencv-library-in-c-subprocess -- you may need to su to root to uninstall."
	exit 1
    else
	echo "/usr/bin/mythryl-opencv-library-in-c-subprocess successfully removed."
    fi
fi


if [ -x /usr/bin/mythryl-ncurses-library-in-c-subprocess ]; then
    rm  /usr/bin/mythryl-ncurses-library-in-c-subprocess

    if [ -x /usr/bin/mythryl-ncurses-library-in-c-subprocess ]; then
	echo "Couldn't rm /usr/bin/mythryl-ncurses-library-in-c-subprocess -- you may need to su to root to uninstall."
	exit 1
    else
	echo "/usr/bin/mythryl-ncurses-library-in-c-subprocess successfully removed."
    fi
fi


if [ -x /usr/bin/mythryl-gtk-library-in-c-subprocess ]; then
	    rm  /usr/bin/mythryl-gtk-library-in-c-subprocess

	    if [ -x /usr/bin/mythryl-gtk-library-in-c-subprocess ]; then
		echo "Couldn't rm /usr/bin/mythryl-gtk-library-in-c-subprocess -- you may need to su to root to uninstall."
		exit 1
	    else
		echo "/usr/bin/mythryl-gtk-library-in-c-subprocess successfully removed."
	    fi
	fi

# Do not edit this or preceding lines --- they are autobuilt.
####################################################################################














if [ -x /usr/bin/build-an-executable-mythryl-heap-image ]; then
    rm  /usr/bin/build-an-executable-mythryl-heap-image

    if [ -x /usr/bin/build-an-executable-mythryl-heap-image ]; then
	echo "Couldn't rm /usr/bin/build-an-executable-mythryl-heap-image -- you may need to su to root to uninstall."
	exit 1
    else
	echo "/usr/bin/build-an-executable-mythryl-heap-image successfully removed."
    fi
fi

echo "Uninstall complete."

exit 0
