#! /usr/bin/perl -w
use strict;

# 2006-04-26 CrT: Simple script implementing 'make tar' functionality.

my $pwd = `pwd`;   chomp $pwd;

unless ($pwd =~ m|/mythryl7.110.58$|) {
    print "Sorry -- must be in 'mythryl7.110.58' directory\n";
    exit 1;
} 

chdir "..";
$pwd = `pwd`;   chomp $pwd;

my $mythryl7version = '';

if ($pwd =~ m|/([^/]+)$|) {
    $mythryl7version = $1; 
} else {
    print "Sorry -- couldn't get name of parent directory to 'mythryl7.110.58'\n";
    exit 1;
}

# Incorporating the date and time in the tarball
# filename keeps us from clobbering previous tarballs:
my $time = `date +"%Y-%m-%d-%T"`;   chomp( $time );

# Shell dislikes colons in filenames, so change to dots:
$time =~ tr/:/./;

# Construct full name for tarball:
my $tarfile = "$mythryl7version-$time.tbz";

print "Creating tarball $tarfile...\n";

`tar -cjf $tarfile mythryl7.110.58`;

print 'DONE: ' . `ls -l $tarfile`;

exit 0;

