#!/bin/sh

								# make_mythryl_compiler		is from   src/app/makelib/mythryl-compiler-compiler/mythryl-compiler-compiler-g.pkg
# Recompile 'make_compiler' (if necessary)
# and then run it:
#
bin/mythryld src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-this-platform.lib <<EOF
    makelib::make ();
EOF

exit 0

