#!/bin/sh

# Install mythryl globally (/usr/bin &tc)
# from local files.  You'll need to be root
# to run this, most likely.

SHELL=/bin/sh

REAL_PWD=`pwd`
ROOT=${PWD:-$REAL_PWD}
SCRIPTS_DIR=$ROOT/sh


# Created 2007-03-15 CrT under LGPL.

#
# Before actually doing anything, make sure
# we have everything in hand to do a complete,
# functional install:

if [ ! -x bin/runtime7 ]; then
    echo "No bin/runtime7 executable found -- did you do 'make compiler'?"
    exit 1
fi

if [ ! -x bin/mythryl ]; then
    echo "No bin/mythryl executable found -- did you do 'make compiler'?"
    exit 1
fi

if [ ! -x bin/mythryld ]; then
    echo "No bin/mythryld executable found -- did you do 'make compiler'?"
    exit 1
fi

if [ ! -x bin/set-heapdump-shebang ]; then
    echo "No bin/set-heapdump-shebang executable found -- did you do 'make compiler'?"
    exit 1
fi

if [ ! -d /usr/bin ]; then
    echo "No /usr/bin directory exists -- what is this machine?"
    exit 1
fi

if [ -f /usr/bin/runtime7 ]; then
    mv /usr/bin/runtime7 /usr/bin/runtime7.old
    if [ -f /usr/bin/runtime7 ]; then
        echo "Couldn't rename /usr/bin/runtime7 to /usr/bin/runtime7.old -- you may need to su to root to install."
        exit 1
    fi
fi

if [ -f /usr/bin/ld7 ]; then
    mv /usr/bin/ld7 /usr/bin/ld7.old
    if [ -f /usr/bin/ld7 ]; then
        echo "Couldn't rename /usr/bin/ld7 to /usr/bin/ld7.old -- you may need to su to root to install."
        exit 1
    fi
fi

if [ -f /usr/bin/mythryl ]; then
    mv /usr/bin/mythryl /usr/bin/mythryl.old
    if [ -f /usr/bin/mythryl ]; then
        echo "Couldn't rename /usr/bin/mythryl to /usr/bin/mythryl.old -- you may need to su to root to install."
        exit 1
    fi
fi

if [ -f /usr/bin/mythryld ]; then
    mv /usr/bin/mythryld /usr/bin/mythryld.old
    if [ -f /usr/bin/mythryld ]; then
        echo "Couldn't rename /usr/bin/mythryld to /usr/bin/mythryld.old -- you may need to su to root to install."
        exit 1
    fi
fi

if [ -f /usr/bin/mythryl-gtk-slave ]; then
    mv /usr/bin/mythryl-gtk-slave /usr/bin/mythryl-gtk-slave.old
    if [ -f /usr/bin/mythryl-gtk-slave ]; then
        echo "Couldn't rename /usr/bin/mythryl-gtk-slave to /usr/bin/mythryl-gtk-slave.old -- you may need to su to root to install."
        exit 1
    fi
fi

cp bin/runtime7 /usr/bin/runtime7
chmod 755       /usr/bin/runtime7
if [ ! -x /usr/bin/runtime7 ]; then
    echo "Couldn't install /usr/bin/runtime7 -- you may need to su to root to install."
    exit 1
fi

cp bin/ld7 /usr/bin/ld7
chmod 755       /usr/bin/ld7
if [ ! -x /usr/bin/ld7 ]; then
    echo "Couldn't install /usr/bin/ld7 -- you may need to su to root to install."
    exit 1
fi

cp bin/mythryl /usr/bin/mythryl
chmod 755      /usr/bin/mythryl
if [ ! -x /usr/bin/mythryl ]; then
    echo "Couldn't install /usr/bin/mythryl -- you may need to su to root to install."
    exit 1
fi

cp bin/mythryld /usr/bin/mythryld
chmod 755       /usr/bin/mythryld
if [ ! -x /usr/bin/mythryld ]; then
    echo "Couldn't install /usr/bin/mythryld -- you may need to su to root to install."
    exit 1
fi
if [ -L /usr/bin/my ]; then
    rm /usr/bin/my
fi
if [ ! -e bin/my ]; then
    ln -s /usr/bin/mythryld /usr/bin/my
fi

bin/set-heapdump-shebang /usr/bin/mythryld '#!/usr/bin/runtime7 --shebang\n'

if [ -x bin/mythryl-gtk-slave ]; then
    cp bin/mythryl-gtk-slave /usr/bin/mythryl-gtk-slave
    chmod 755        /usr/bin/mythryl-gtk-slave
fi

# Function to install a script.
#   This takes care of patching the source
#   of the script with the SHELL and BIN_DIR
#   variables to use.
#
patch_and_install_script() {
    dsrc=$1
    ddst=$2

    rm -f "/usr/bin"/"$ddst"
    cat "$SCRIPTS_DIR"/"$dsrc" | \
    sed -e "s,@SHELL@,$SHELL,g" \
	-e "s,@BIN_DIR@,/usr/bin," \
	> "/usr/bin"/"$ddst"
    chmod 555 "/usr/bin"/"$ddst"
    if [ ! -x "/usr/bin"/"$ddst" ]; then
	complain "                         sh/make-c-stuff:   Installation of /usr/bin/${ddst} failed."
    fi
}

patch_and_install_script _build-an-executable-mythryl-heap-image build-an-executable-mythryl-heap-image


echo "Installed in /usr/bin:"
ls -l /usr/bin/runtime7 /usr/bin/ld7 /usr/bin/mythryl /usr/bin/my /usr/bin/mythryld /usr/bin/mythryl-gtk-slave /usr/bin/build-an-executable-mythryl-heap-image

exit 0
