#!/bin/sh

# Re/compile all source code that
# goes into the Mythryl compiler.
											# mythryl_compiler_compiler_for_this_platform	is set by   src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-this-platform.lib
											#                                               to one of:
											# mythryl_compiler_compiler_for_intel32_posix	is from   src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-intel32-posix.pkg
											# mythryl_compiler_compiler_for_intel32_win32	is from   src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-intel32-win32.pkg
											# mythryl_compiler_compiler_for_pwrpc32_macos	is from   src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-pwrpc32-macos.pkg
											# mythryl_compiler_compiler_for_pwrpc32_posix	is from   src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-pwrpc32-posix.pkg
											# mythryl_compiler_compiler_for_sparc32_posix	is from   src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-sparc32-posix.pkg
								#                                                                                        ...
# Recompile 'mythryl_compiler_compiler_for_this_Platform'
# (if necessary) and then run it.


# First, select compiler image to use.
#
# bin/mythryld is the "executable" heap image containing
# the compiled Mythryl code for the compiler etc.
#
# We may have up to four versions of it floating around:
#
#     bin/mythryld-bootstrap   The downloaded seed version used to get started.
#     bin/mythryld-bare        The first locally-compiled version, containing just the essentials.
#     bin/mythryld.previous    The previous version of bin/mythryld -- first fallback if bin/mythryld is missing or broken.
#     bin/mythryld             The most recently compiled version, containing all goodies requested via sh/addglue
#
# Use any of the above, in
# reverse order of preference:

if [ -f bin/mythryld ]; then
    mythryld=bin/mythryld
else
    if [ -f bin/mythryld-bare ]; then
        mythryld=bin/mythryld-bare
    else
	if [ -f bin/mythryld.previous ]; then
	    mythryld=bin/mythryld.previous
	else
	    if [ -f bin/mythryld-bootstrap ]; then
		mythryld=bin/mythryld-bootstrap
	    else
		echo "bin/mythryld does not exist."
		echo "bin/mythryld.previous does not exist."
		echo "bin/mythryld-bare does not exist."
		echo "bin/mythryld-bootstrap does not exist."
		echo "How can I compile anything? Giving up."
		echo "      -- sh/make-compiler-libraries"
		exit 1;
	    fi
	fi
    fi
fi

"$mythryld"  src/lib/core/mythryl-compiler-compiler/mythryl-compiler-compiler-for-this-platform.lib  <<EOF
    mythryl_compiler_compiler_for_this_platform::make_mythryl_compiler ();
EOF

exit 0

