#!/bin/sh

# For sparc32 we synthesize the sourcefiles
#
#     src/lib/compiler/back/low/sparc32/code/machcode-sparc32.codemade.api
#     src/lib/compiler/back/low/sparc32/code/machcode-sparc32-g.codemade.pkg
#     src/lib/compiler/back/low/sparc32/code/registerkinds-sparc32.codemade.pkg
#     src/lib/compiler/back/low/sparc32/emit/translate-machcode-to-asmcode-sparc32-g.codemade.pkg
#     src/lib/compiler/back/low/sparc32/emit/translate-machcode-to-execode-sparc32-g.codemade.pkg
#
# from the more abstract Architecture Description File
#
#    src/lib/compiler/back/low/sparc32/sparc32.architecture-description
#
# See comments in latter file for more detail.
#
# Our job in this file is to do this code synthesis.
#
# We are normally invoked as needed by the
#
#     : shell (source: ../sparc32/sparc32.architecture-description options:shared sh/make-sourcecode-for-backend-sparc32)
#
# makelib qualifiers in
#
#     src/lib/compiler/back/low/sparc32/backend-sparc32.lib
#
# but that makelib functionality is broken at present,
# hence commented out -- we just invoke this script
# manually whenever we change sun.architecture-description
#
# When makelib gets fixed, the
#
#     @find . -type f -name '*.codemade.*' -print | xargs rm -f;
#                
# line in the main Makefile should be uncommented.
#
# In the meantime, this script gets run every development cycle by the
#     backends:
# target in Makefile, just to guard against creeping bitrot.
#
#                     -- 2011-05-18 CrT 

bin/mythryld  src/lib/compiler/back/low/tools/arch/make-sourcecode-for-backend-packages.lib  <<EOF
    #
    package s32 = make_sourcecode_for_backend_sparc32;
    s32::make_sourcecode_for_backend_sparc32  "src/lib/compiler/back/low/sparc32/sparc32.architecture-description";
EOF

exit 0

