#!/bin/sh

# Our compiled Mythryl 'executables' are actually just
# heap dumps:  The only thing that makes them 'executable'
# is a
#
#     #!/mumble/bin/mythryl --shebang
#
# line at the top which triggers the Unix script-execution
# mechansim.
#
# But for this to work, the shebang lines must point to
# where our
#
#     bin/mythryl
#
# C wrapper program -- see the source in
#
#     src/runtime/o/mythryl.c
#
# -- is actually located, which will depend on where
# the user unpacked the distribution tarball.
#
# So our job in this script is to patch correct shebang
# lines into the Mythryl "executables" given on our
# commandline.
#
# The dirty low-level work is actually done by
#
#     bin/set-heapdump-shebang
#
# from
#
#     src/runtime/o/set-heapdump-shebang.c
#
# -- we're just a convenience wrapper:


cwd=`pwd`
shebang_line="#!$cwd/bin/runtime7 --shebang"

# Iterate over all command line arguments:
#
while [ "$#" != 0 ] ; do

    prog=$1; shift

    if  [ -r $prog ]
    then
	echo
	echo "                       sh/patch-shebangs:   Making $prog executable by pointing its shebang line to bin/runtime7:"
	echo "                       sh/patch-shebangs:   Doing 'bin/set-heapdump-shebang $prog \"$shebang_line\"'"
	bin/set-heapdump-shebang $prog "$shebang_line"
    fi
done
echo "                       sh/patch-shebangs:   Done."

exit 0;

