#!/bin/sh
#
# Install-time build script for inet-lib.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/internet/inet-lib.make6.frozen.

bin/mythryld <<EOF
    make7::freeze "src/lib/internet/inet-lib.make6";
EOF

if   [ -f "src/lib/internet/inet-lib.make6.frozen" ]
then
     echo "                  src/lib/internet/build:   Successfully created src/lib/internet/inet-lib.make6.frozen:"
     echo "                  src/lib/internet/build:   `ls -l src/lib/internet/inet-lib.make6.frozen`"
else
     echo "                  src/lib/internet/build:   Failed to create src/lib/internet/inet-lib.make6.frozen"
     exit 1
fi

exit 0;
