#!/bin/sh
#
# Install-time build script for internet.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/internet/internet.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/internet/internet.lib";
EOF

if [ -f "src/lib/internet/internet.lib.frozen" ]
then
    echo "                  src/lib/internet/build:   Successfully created    src/lib/internet/internet.lib.frozen:"
    echo "                  src/lib/internet/build:                           `ls -l src/lib/internet/internet.lib.frozen`"
else
    echo "                  src/lib/internet/build:   FAILED TO CREATE        src/lib/internet/internet.lib.frozen"
    exit 1
fi

exit 0;
