#!/bin/sh
#
# Install-time build script for bouncing-heads-app.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/x-kit/tut/bounce/bouncing-heads-app.make6.frozen.

bin/mythryld <<EOF
    make7::freeze "src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.make6";
EOF

if   [ -f "src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.make6.frozen" ]
then
     echo "            build-bouncing-heads-app:   Successfully created: src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.make6.frozen"
     echo "            build-bouncing-heads-app:   `ls -l src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.make6.frozen`"
else
     echo "            build-bouncing-heads-app:   Failed to create src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.make6.frozen"
     exit 1
fi

exit 0;
