
LIBRARY_EXPORTS

	api GENERATE_FILE
	api MDL_ERROR
	api SOURCE_MAPPING
	api UNIQUE_SYMBOL

	pkg GenFile
	pkg mdl_error
	pkg SourceMapping
	pkg UniqueSymbol



LIBRARY_COMPONENTS

        $ROOT/src/lib/std/stdlib.make6

	error.api
	error.pkg
	symbol.api
	symbol.pkg
	source-map.api
	source-map.pkg
	gen-file.api
	gen-file.pkg
