#!/bin/sh
PROGS="arrows cal calendar entry hello \
      helloworld menu notebook paned \
      pop-ups rangewidgets scrolledwin spinbutton \
      statusbar text gadgets help-menu help-menu2 \
      calc item-factory accel-menu
     "

for prog in $PROGS ; do

   sml <<END || exit 1
use "init.pkg";
use "$prog.sml";
SMLofNJ.exportFn("$prog",main);
END

done
