## Makefile.make6

# Compiled by:
#     src/lib/thread-kit/src/unix/winix.make6

LIBRARY_GROUP_EXPORTS



LIBRARY_GROUP_COMPONENTS

	$ROOT/src/lib/std/stdlib.make6				# 2009-11-14 CrT: Was lib7 prior to lib7/stdlib merge.
#       $ROOT/src/lib/thread-kit/src/core-threadkit.make6


        thread-result.pkg



# COPYRIGHT (c) 1996 AT&T Research.
# Subsequent changes by Jeff Prothero Copyright (c) 2010,
# released under Gnu Public Licence version 3.
