#!/bin/sh
#
# Install-time build script for portable-graph-stuff.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/app/makelib/portable-graph-stuff.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/app/makelib/portable-graph/portable-graph-stuff.lib";
EOF

if [ -f "src/app/makelib/portable-graph/portable-graph-stuff.lib.frozen" ]
then
    echo "              build-portable-graph-stuff:   Successfully created    src/app/makelib/portable-graph/portable-graph-stuff.lib.frozen:"
    echo "              build-portable-graph-stuff:                           `ls -l src/app/makelib/portable-graph/portable-graph-stuff.lib.frozen`"
else
    echo "              build-portable-graph-stuff:   FAILED TO CREATE        src/app/makelib/portable-graph/portable-graph-stuff.lib.frozen"
    exit 1
fi

exit 0;
