LIBRARY_GROUP_EXPORTS



LIBRARY_GROUP_COMPONENTS 

        $ROOT/src/lib/std/stdlib.make6

	$ROOT/src/lib/compiler/backend/lower/make7/control.make6
	$ROOT/src/lib/compiler/backend/lower/make7/lib.make6
	$ROOT/src/lib/compiler/backend/lower/make7/lowcode.make6
	$ROOT/src/lib/compiler/backend/lower/make7/sparc.make6

	spill-table-g.pkg

	# Common type definitions:
	demo-types.pkg	   

	# Generic backend:
	demo-backend.pkg   

	# Backend specialized to sparc instructions:
	demo-sparc.pkg	   
