LIBRARY_GROUP_EXPORTS



LIBRARY_GROUP_COMPONENTS 

        /* standard basis */
        $ROOT/src/lib/std/stdlib.make6

         parse-control.api
         type-check-control.api
         config-sig.pkg

	#if (defined(d))
        d/config.pkg
	#elif (defined(fiveessc))
        5essc/config.pkg
	#else
        ansi-c/config.pkg
	#endif
