#!/bin/sh
#
# Install-time build script for prec-parser.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/compiler/backend/lower/tools/prec-parser.make6.frozen.

bin/mythryld <<EOF
    make7::freeze "src/lib/compiler/backend/lower/tools/prec-parser.make6";
EOF

if   [ -f "src/lib/compiler/backend/lower/tools/prec-parser.make6.frozen" ]
then
     echo "       .../backend/lower/tools/build-prec-parser:   Successfully created src/lib/compiler/backend/lower/tools/prec-parser.make6.frozen:"
     echo "       .../backend/lower/tools/build-prec-parser:   `ls -l src/lib/compiler/backend/lower/tools/prec-parser.make6.frozen`"
else
     echo "       .../backend/lower/tools/build-prec-parser:   Failed to create src/lib/compiler/backend/lower/tools/prec-parser.make6.frozen"
     exit 1
fi

exit 0;
