// generate-posix-signal-table-c.c
//
// Generate the "posix-signal-table--autogenerated.c" file,
// which will be #included by
//
//     src/c/machine-dependent/posix-signal.c

#include "../mythryl-config.h"

#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include "header-file-autogeneration-stuff.h"
#include "generate-system-signals.h-for-posix-systems.h"

#ifndef DST_FILE
#define DST_FILE "posix-signal-table--autogenerated.c"
#endif

int main (void)
{
    int		i;

    char*        filename      =  DST_FILE;
    char*        unique_string =  NULL;
    char*        progname      =  "src/c/config/generate-posix-signal-table-c.c";

    Runtime_System_Signal_Table*  signal_info   =  sort_runtime_system_signal_table ();

    int		 signal_count  =  signal_info->posix_signal_kinds;

    FILE*	 f = start_generating_header_file( filename, unique_string, progname	);				// start_generating_header_file	is from   src/c/config/start-and-finish-generating-header-file.c

    fprintf (f, "\n");
    fprintf (f, "// This file will be #included by:\n");
    fprintf (f, "// \n");
    fprintf (f, "//    src/c/machine-dependent/posix-signal.c\n");
    fprintf (f, "\t\t\t\t\t\t\t\t\t\t\t// System_Constant\tis from   src/c/h/runtime-base.h\n");
    fprintf (f, "static System_Constant   signal_sysconsts_table_guts__local[ NUM_SIGS ] = {\t\t// NUM_SIGS\t\tis from   src/c/o/system-signals--autogenerated.h\n");

    for (i = 0;  i < signal_info->posix_signal_kinds;  i++) {
        //
	fprintf(f, "    { %s, \"%s\" },\n",
	    signal_info->sigs[i]->signal_h__name_for_signal,
	    signal_info->sigs[i]->mythryl_name_for_signal
        );
    }
    fprintf (f, "  // Run-time signals\n");

    for (i = signal_info->posix_signal_kinds;  i < signal_count;  i++) {
        //
        fprintf(f, "    { %s, \"%s\" },\n",
	    signal_info->sigs[i]->signal_h__name_for_signal,
	    signal_info->sigs[i]->mythryl_name_for_signal
        );
    }

    fprintf (f, "};\n");
    fprintf (f, "static Sysconsts   signal_sysconsts_table__local = {\n");
    fprintf (f, "    /* constants_count  */ NUM_SIGS,\n");
    fprintf (f, "    /* constants_vector */ signal_sysconsts_table_guts__local\n");
    fprintf (f, "};\n");

    finish_generating_header_file( f, unique_string );

    exit (0);

}

// COPYRIGHT (c) 1995 by AT&T Bell Laboratories.
// Subsequent changes by Jeff Prothero Copyright (c) 2010-2012,
// released under Gnu Public Licence version 3.

