// generate-posix-signal-table-c.c
//
// Generate the "posix-signal-table--autogenerated.c" file.


#include "../mythryl-config.h"

#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include "header-file-autogeneration-stuff.h"
#include "generate-system-signals.h-for-posix-systems.h"

#ifndef DST_FILE
#define DST_FILE "posix-signal-table--autogenerated.c"
#endif

int main (void)
{
    int		i;

    char*        filename      =  DST_FILE;
    char*        unique_string =  NULL;
    char*        progname      =  "src/c/config/generate-posix-signal-table-c.c";

    Runtime_System_Signal_Table*  signal_info   =  sort_runtime_system_signal_table ();
    int		 signal_count  =  signal_info->posix_signal_kinds
                               +  signal_info->runtime_generated_signal_kinds;

    FILE*	 f = start_generating_header_file( filename, unique_string, progname	);				// start_generating_header_file	is from   src/c/config/start-and-finish-generating-header-file.c

    fprintf (f, "\n");
    fprintf (f, "static System_Constant SigInfo[NUM_SIGS] = {\n");
    for (i = 0;  i < signal_info->posix_signal_kinds;  i++) {
	fprintf(f, "    { %s, \"%s\" },\n",
	    signal_info->sigs[i]->sigName, signal_info->sigs[i]->shortName);
    }
    fprintf (f, "  // Run-time signals\n");

    for (i = signal_info->posix_signal_kinds;  i < signal_count;  i++) {
        fprintf(f, "    { %s, \"%s\" },\n", signal_info->sigs[i]->sigName, signal_info->sigs[i]->shortName);
    }

    fprintf (f, "};\n");
    fprintf (f, "static System_Constants_Table SigTable = {\n");
    fprintf (f, "    /* constants_count */ NUM_SIGS,\n");
    fprintf (f, "    /* consts */    SigInfo\n");
    fprintf (f, "};\n");

    finish_generating_header_file( f, unique_string );

    exit (0);

}

// COPYRIGHT (c) 1995 by AT&T Bell Laboratories.
// Subsequent changes by Jeff Prothero Copyright (c) 2010-2011,
// released under Gnu Public Licence version 3.

