#!/bin/sh
#
# Install-time build script for register-spilling.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/compiler/back/low/lib/register-spilling.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/compiler/back/low/lib/register-spilling.lib";
EOF

if [ -f "src/lib/compiler/back/low/lib/register-spilling.lib.frozen" ]
then
    echo "             build-register-spilling-lib:   Successfully created    src/lib/compiler/back/low/lib/register-spilling.lib.frozen:"
    echo "             build-register-spilling-lib:                           `ls -l src/lib/compiler/back/low/lib/register-spilling.lib.frozen`"
else
    echo "             build-register-spilling-lib:   FAILED TO CREATE        src/lib/compiler/back/low/lib/register-spilling.lib.frozen"
    exit 1
fi

exit 0;
