#!/bin/sh
#
# Install-time build script for peephole.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/compiler/back/low/lib/peephole.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/compiler/back/low/lib/peephole.lib";
EOF

if [ -f "src/lib/compiler/back/low/lib/peephole.lib.frozen" ]
then
    echo "                          build-peephole:   Successfully created    src/lib/compiler/back/low/lib/peephole.lib.frozen:"
    echo "                          build-peephole:                           `ls -l src/lib/compiler/back/low/lib/peephole.lib.frozen`"
else
    echo "                          build-peephole:   FAILED TO CREATE        src/lib/compiler/back/low/lib/peephole.lib.frozen"
    exit 1
fi

exit 0;
