#!/bin/sh
#
# Install-time build script for lexgen.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the executable bin/lexgen.
#
# options:
#   -o image		-- specify the name of the heap image, "mythryl-yacc"
#			   is the default.

CMD=$0

LEXGEN="lexgen"
HEAP_IMAGE=""
HERE=`pwd`
cd ../../..
THREE_UP=`pwd`
cd $HERE
BIN=${INSTALL_DIR:-$THREE_UP}/bin
MAKE7=$BIN/build-an-executable-mythryl-heap-image

echo
echo '-----------------------------------------------------'
echo "                src/app/future-lex/build:   Starting."

#
# Process command-line options:
while [ "$#" != "0" ] ; do
    arg=$1
    shift
    case $arg in
	-o)
	    if [ "$#" = "0" ]; then
		echo "                src/app/future-lex/build:   Must supply image name for -o option"
		exit 1
	    fi
	    HEAP_IMAGE=$1; shift
	    ;;
	*)
	    echo "                src/app/future-lex/build:   Invalid argument: $arg"
	    exit 1
	    ;;
    esac
done

if [ "$HEAP_IMAGE" = "" ]; then
    HEAP_IMAGE="$LEXGEN"
fi

echo "                src/app/future-lex/build:   Entering `pwd`/src"
cd src

echo "                src/app/future-lex/build:   Doing:                  $MAKE7 Lexgen.make6 main.main $HEAP_IMAGE"
"$MAKE7" Lexgen.make6 main.main "$HEAP_IMAGE"

if [ -f "$HEAP_IMAGE" ]; then

    echo "                src/app/future-lex/build:   $HEAP_IMAGE created."

    if [ -f "$BIN/$LEXGEN.old" ]; then
        echo "                src/app/future-lex/build:   Removing $BIN/$LEXGEN.old"
        rm $BIN/$LEXGEN.old
    fi

    if [ -f "$BIN/$LEXGEN" ]; then
        echo "                src/app/future-lex/build:   Saving $BIN/$LEXGEN as $BIN/$LEXGEN.old"
        mv "$BIN/$LEXGEN" "$BIN/$LEXGEN.old"
    fi

    echo "                src/app/future-lex/build:   Installing $HEAP_IMAGE as $BIN/$LEXGEN"
    cp "$HEAP_IMAGE" "$BIN/$LEXGEN"
    chmod +x "$BIN/$LEXGEN"
    rm "$HEAP_IMAGE"

else
    echo "                src/app/future-lex/build:   $HEAP_IMAGE not created, aborting."
    exit 1
fi



echo "                src/app/future-lex/build:   Done."
echo
echo
echo

exit 0
