#!/usr/bin/perl -w
use strict;



# Find all pkg definition files produced by sh/make-api-latex:
#
my $errors = 0;
my @pkg_files = `ls -1 doc/tex/tmp-pkg*tex`;
my $pkg_files_count = scalar @pkg_files;
if ($pkg_files_count < 100) {
    print "Only $pkg_files_count PKG docfiles doc/tex/tmp-pkg*tex found -- something's wrong.\n";
    print @pkg_files;
    exit 1;
}

# Find all book pkg-section files:
#
my @section_files = `ls -1 doc/tex/section-pkg-*tex`;
my $section_files_count = scalar @section_files;
if ($section_files_count < 1) {
    print "Only $section_files_count book sections doc/tex/section-pkg-*tex found -- something's wrong.\n";
    exit 1;
}

# my @pkg_file_references = `egrep '\\input\{tmp-pkg-.*\.tex\}' doc/tex/section-pkg-*tex`;
# my $pkg_file_references_count = scalar @pkg_file_references;
# print "found $pkg_file_references_count pkg file references in book sections\n";

# Make a hash of the names of all defined pkgs:
#
my %pkg_definition = ();
for my $pkg_file (@pkg_files) {
    chomp $pkg_file;
    if ($pkg_file =~ /tmp-pkg-(.*)\.tex/) {
         my $pkg_name = $1;
         $pkg_definition{ $pkg_name } = $pkg_file;
    }
}

my %pkg_reference = ();

# Check for section-file references to non-existent pkg files:
#
for my $section_file (@section_files) {

    chomp $section_file;

    my @pkg_file_references
        =
        `egrep '\\input\{tmp-pkg-.*\.tex\}' $section_file`;

    for my $pkg_ref (@pkg_file_references) {

	chomp $pkg_ref;

        # TeX requires that all underbars be \'d
        # so here we undo that for readability:
        $pkg_ref =~ s/\\_/_/g;

	if ($pkg_ref =~ /tmp-pkg-(.*)\.tex/) {

	     my $pkg_name = $1;
	     $pkg_reference{ $pkg_name } = $pkg_ref;
             unless (defined $pkg_definition{ $pkg_name }) {
                 ++ $errors;
                 print "Error: pkg file $pkg_ref referenced by $section_file DOES NOT EXIST!\n";
             }
	 }
    } 
}

# Check for defined pkgs not mentioned in any pkg-section file:
#
for my $pkg_name (keys %pkg_definition) {
    if (not defined $pkg_reference{ $pkg_name }) {
	++ $errors;
	print "Error: pkg $pkg_name defined in file $pkg_definition{ $pkg_name } is not mentioned in any PKG section!\n";
    }
}

if ($errors) {
    print "$errors errors detected.\n";
} else {
#   print      "No errors detected.\n";
}

exit $errors;
