#!/usr/bin/perl -w
use strict;



###                   "The camel has evolved to be
###                    relatively self-sufficient.
###
###                   "On the other hand, the camel
###                    has not evolved to smell good.
###
###                   "Neither has Perl."
###
###                                -- Larry Wall


# Find all api definition files produced by sh/make-api-latex:
#
my $errors = 0;
my @api_files = `ls -1 doc/tex/tmp-api*tex`;
my $api_files_count = scalar @api_files;
if ($api_files_count < 100) {
    print "Only $api_files_count API docfiles doc/tex/tmp-api*tex found -- something's wrong.\n";
    print @api_files;
    exit 1;
}

# Find all book api-section files:
#
my @section_files = `ls -1 doc/tex/section-api-*tex`;
my $section_files_count = scalar @section_files;
if ($section_files_count < 3) {
    print "Only $section_files_count book sections doc/tex/section-api-*tex found -- something's wrong.\n";
    exit 1;
}

# my @api_file_references = `egrep '\\input\{tmp-api-.*\.tex\}' doc/tex/section-api-*tex`;
# my $api_file_references_count = scalar @api_file_references;
# print "found $api_file_references_count api file references in book sections\n";

# Make a hash of the names of all defined apis:
#
my %api_definition = ();
for my $api_file (@api_files) {
    chomp $api_file;
    if ($api_file =~ /tmp-api-(.*)\.tex/) {
         my $api_name = $1;
         $api_definition{ $api_name } = $api_file;
    }
}

my %api_reference = ();

# Check for section-file references to non-existent api files:
#
for my $section_file (@section_files) {					# Over all   doc/tex/section-api-*tex   files found.
    #
    chomp $section_file;

    my @api_file_references
        =
        `egrep '\\input\{tmp-api-.*\.tex\}' $section_file`;

    for my $api_ref (@api_file_references) {
	#
	chomp $api_ref;

        # TeX requires that all underbars be \'d
        # so here we undo that for readability:
        $api_ref =~ s/\\_/_/g;

	if ($api_ref =~ /tmp-api-(.*)\.tex/) {
	    #
	     my $api_name = $1;
	     $api_reference{ $api_name } = $api_ref;
             unless (defined $api_definition{ $api_name }) {
                 ++ $errors;
                 print "Error: api file $api_ref referenced by $section_file DOES NOT EXIST!\n";
             }
	 }
    } 
}

# Check for defined apis not mentioned in any api-section file:
#
for my $api_name (keys %api_definition) {
    if (not defined $api_reference{ $api_name }) {
	++ $errors;
	print "Error: api $api_name defined in file $api_definition{ $api_name } is not mentioned in any API section!\n";
    }
}

if ($errors) { 
    print "$errors errors detected.\n";
} else {
#   print      "No errors detected.\n";
}

exit $errors;
