#!/usr/bin/perl -w
use strict;

# Yeah, there's probably a one-liner to do this using the range operator.
# So email it to me.

my $arg_count   =  scalar @ARGV;	die "Usage: drop-footer filename" if $arg_count != 1;
my $input_file  =  $ARGV[0];		die "$input_file does not exist!" if not -f $input_file;
my $output_file =  "$input_file~";	# Because 'make clean' will remove all tilda files.

open IN,    "$input_file" || die "Cannot read $input_file!\n";
open OUT, ">$output_file" || die "Cannot write $output_file!\n";

while (my $line = <IN>) {
    last  if   $line =~ /^<!--FOOTER-->$/;
    print OUT $line;
}

print OUT "</HTML>\n";

close OUT || die "Couldn't close $output_file?!";
close IN;

rename ($input_file, "$input_file.bak~");
rename ($output_file, $input_file);

exit 0;



