#!/bin/sh

cd doc/tex
mkdir deletable-directory
cp *.html deletable-directory
cp *.gif  deletable-directory
cp *.jpg  deletable-directory
cp *.css  deletable-directory
cd deletable-directory
rm -f book.html
tar -cjf ../mythryl.tbz .
cd ..
rm -rf deletable-directory

