#! /usr/bin/perl -w
use strict;

# 2009-03-04 CrT: Simple script to build a distribution tarball.

my $pwd = `pwd`;   chomp $pwd;

unless ($pwd =~ m|/mythryl7.110.58$|) {
    print "Sorry -- must be in 'mythryl7.110.58' directory\n";
    exit 1;
} 



# Remove bin/mythryld and rename bin/mythryld-bare to bin/mythryld-bootstrap:
#
if (-f "bin/mythryld") {
    system "rm -f bin/mythryld"                                and   die "Could not  rm -f bin/mythryld";
}
if (-f "bin/mythryld-bare") {
    system "mv -f bin/mythryld-bare bin/mythryld-bootstrap"    and   die "Could not  mv bin/mythryld-bare bin/mythryld-bootstrap";
}


chdir "..";
$pwd = `pwd`;   chomp $pwd;

my $mythryl7version = '';

if ($pwd =~ m|/([^/]+)$|) {
    $mythryl7version = $1; 
} else {
    print "Sorry -- couldn't get name of parent directory to 'mythryl7.110.58'\n";
    exit 1;
}

# Incorporating the date and time in the tarball
# filename keeps us from clobbering previous tarballs:
my $time = `date +"%Y-%m-%d-%T"`;   chomp( $time );

# Shell dislikes colons in filenames, so change to dots:
$time =~ tr/:/./;

# Construct full name for tarball:
my $tarfile = "$mythryl7version-$time.tar";
my $tarbz2file = "$mythryl7version-dist-$time.tar.bz2";

print "Creating tarball $tarfile...\n";

`tar -cf $tarfile mythryl7.110.58`;

if (-d "disposable-directory") {
   `rm -rf disposable-directory`;
}
`mkdir  disposable-directory`;
`mv $tarfile disposable-directory`;
 chdir "disposable-directory";
`tar -xf $tarfile`;
 chdir "$mythryl7version";
`rm -rf doc`;
`egrep -v doc/tex <Makefile >Makefile~`;
`rm Makefile`;
`mv Makefile~ Makefile`;
 chdir "..";
`tar -cjf ../$tarbz2file mythryl7.110.58`;
 chdir "..";
`rm -rf disposable-directory`;

print 'DONE: ' . `ls -l $tarbz2file`;

print "Hope you updated src/lib/core/internal/mythryl-compiler-version.pkg\n";
print "You may now want to do:  scp ../$tarbz2file cynbe\@laurel.muq.org:/usr/home/www-data/webspace/mythryl/download\n";

exit 0;


