#!/bin/sh

scp doc/tex/mythryl.tbz cynbe@laurel.muq.org:/usr/home/www-data/webspace/mythryl
ssh laurel.muq.org '(cd /usr/home/www-data/webspace/mythryl; tar -xjf mythryl.tbz; rm mythryl.tbz)'

exit 0
