#!/usr/bin/perl -w
use strict;

# I couldn't find a way to persuade hevea to index symbols like "foo'" or "foo!"
# so instead I had  backslash_latex_special_chars()  in
#     src/lib/compiler/front/typer/print/latex-print-value.pkg
# change them to __prime__ and __bang__ respectively.
#
# This script reverses that hack on the synthesized html,
# giving us something readable back.
#
# This script gets invoked by ../Makefile.
# 

my $arg_count   =  scalar @ARGV;	die "Usage: drop-footer filename" if $arg_count != 1;
my $input_file  =  $ARGV[0];		die "$input_file does not exist!" if not -f $input_file;
my $output_file =  "$input_file~";	# Because 'make clean' will remove all tilda files.

open IN,    "$input_file" || die "Cannot read $input_file!\n";
open OUT, ">$output_file" || die "Cannot write $output_file!\n";

while (my $line = <IN>) {
    $line =~ s|__prime__|'|g;
    $line =~ s|__bang__|!|g;
    $line =~ s|qQQq|&nbsp;|g;
    print OUT $line;
}

close OUT || die "Couldn't close $output_file?!";
close IN;

rename ($input_file, "$input_file.bak~");
rename ($output_file, $input_file);

exit 0;



