#!/bin/sh

# I dislike the "Chapter [1-9]" tags that Hevea
# produces -- I prefer just the bare text
# title -- and there doesn't seem a trivial
# way of suppressing it at the Hevea level,
# so we just get out our crowbar and:

perl -p -i.bak -e 's|Chapter[^0-9]+[0-9]+\</A\>[^A-Z]+|\</A\>|;'  doc/tex/index.html
perl -p -i.bak -e 's|Appendix[^A-Z]+[A-Z]+\</A\>[^A-Z]+|\</A\>|;' doc/tex/index.html

exit 0
