/* gen-bc-instruction-def.c
 *
 * A program to generate #defines for the bytecode instruction opcodes.
 */

#include "../config.h"

#include <stdio.h>
#include "gen.h"
#include "bc.h"
#include "print-bc.h"

main ()
{
    int		i;
    FILE*	f;

    f = OpenFile ("bc-instruction-def.h", "_BC_INSTR_DEF_");

    fprintf(f, "/* This file auto-generated by src/runtime/config/gen-bc-instruction-def.c -- do not edit. */\n");
    for (i = 0;  i < NUM_BC_INSTRS;  i++) {
	fprintf(f, "#define %-23s %d\n", instrTable[i].instrName, i);
    }

    CloseFile (f, "_BC_INSTR_DEF_");

    exit (0);
}



/* COPYRIGHT (c) 1993 by AT&T Bell Laboratories.
 */
