/* gen-unix-sigtable.c
 *
 * Generate the "unix-sigtable.c" file.
 */

#include "../config.h"

#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include "gen.h"
#include "gen-unix-signals.h"

#ifndef DST_FILE
#define DST_FILE "unix-sigtable.c"
#endif

int main (void)
{
    sig_info_t	    *sigInfo;
    int		    i;
    int		    numSigs;
    FILE	    *f;

    sigInfo = SortSignalTable ();
    numSigs = sigInfo->numSysSigs + sigInfo->numRunSigs;

    f = OpenFile (DST_FILE, NULL);

    fprintf (f, "/* This file autogenerated by src/runtime/config/gen-unix-sigtable.c -- do not edit*/\n");
    fprintf (f, "\n");
    fprintf (f, "static sys_const_t SigInfo[NUM_SIGS] = {\n");
    for (i = 0;  i < sigInfo->numSysSigs;  i++) {
	fprintf(f, "    { %s, \"%s\" },\n",
	    sigInfo->sigs[i]->sigName, sigInfo->sigs[i]->shortName);
    }
    fprintf (f, "  /* Run-time signals */\n");
    for (i = sigInfo->numSysSigs;  i < numSigs;  i++) {
      fprintf(f, "    { %s, \"%s\" },\n",
          sigInfo->sigs[i]->sigName, sigInfo->sigs[i]->shortName);
    }
    fprintf (f, "};\n");
    fprintf (f, "static sysconst_table_t SigTable = {\n");
    fprintf (f, "    /* numConsts */ NUM_SIGS,\n");
    fprintf (f, "    /* consts */    SigInfo\n");
    fprintf (f, "};\n");

    CloseFile (f, NULL);

    exit (0);

} /* end of main */

/* COPYRIGHT (c) 1995 by AT&T Bell Laboratories.
 */
