/* gen-offsets.c
 *
 * This C program generates a header file for the *.prim.asm files,
 * which gives the offset values in the VProc and Lib7 state vectors.
 */

#include "../config.h"

#include "runtime-base.h"
#include "vproc-state.h"
#include "runtime-state.h"
#include "gen.h"

#define MOFFSET(fld)	(((Addr_t)&(M.s.fld)) - (Addr_t)&(M.b[0]))
#define VOFFSET(fld)	(((Addr_t)&(V.s.fld)) - (Addr_t)&(V.b[0]))

#define PVOFFSET(sym, fld)	\
    fprintf(f, "#define %sOffVSP %ld\n", (sym), (long int) VOFFSET(fld))
#define PMOFFSET(sym, fld)	\
    fprintf(f, "#define %sOfflib7_state %ld\n", (sym), (long int) MOFFSET(fld))


int main (void)
{
    union {
	vproc_state_t	s;
	char		b[sizeof(vproc_state_t)];
    }		V;
    union {
	lib7_state_t	s;
	char		b[sizeof(lib7_state_t)];
    }		M;
    FILE	*f;

    f = OpenFile ("lib7state-offsets.h", "_LIB7STATE_OFFSETS_");

    fprintf (f, "/* This file autogenerated by src/runtime/config/gen-offsets.c -- do not edit */\n");
#if TARGET_BYTECODE
    fprintf (f, "/* TARGET_BYTECODE */\n");
#else
    PMOFFSET("VProc", lib7_vproc);
    PMOFFSET("AllocPtr", lib7_heap_cursor);
    PMOFFSET("LimitPtr", lib7_heap_limit);
    PMOFFSET("StorePtr", lib7_store_log);
    PMOFFSET("StdArg", lib7_argument);
    PMOFFSET("StdCont", lib7_fate);
    PMOFFSET("StdClos", lib7_closure);
    PMOFFSET("LinkReg", lib7_link_register);
    PMOFFSET("PC", lib7_program_counter);
    PMOFFSET("ExnPtr", lib7_exception_fate);
    PMOFFSET("CurrentThreadPtr", lib7_current_thread);
    PMOFFSET("Misc0", lib7_calleeSave[0]);
    PMOFFSET("Misc1", lib7_calleeSave[1]);
    PMOFFSET("Misc2", lib7_calleeSave[2]);
#ifdef SOFT_POLL
    PMOFFSET("RealLimit", lib7_real_heap_limit);
    PMOFFSET("PollPending", lib7_poll_event_is_pending);
    PMOFFSET("InPollHandler", lib7_in_poll_handler);
#endif
    PVOFFSET("InLib7", vp_inLib7Flag);
    PVOFFSET("LimitPtrMask", vp_limitPtrMask);
    PVOFFSET("HandlerPending", vp_handlerPending);
    PVOFFSET("InSigHandler", vp_inSigHandler);
    PVOFFSET("SigsRecv", vp_totalSigCount.nReceived);
    PVOFFSET("SigsHandled", vp_totalSigCount.nHandled);
#endif /* !BYTECODE */

    CloseFile (f, "_LIB7STATE_OFFSETS_");

    exit (0);
}



/* COPYRIGHT (c) 1992 by AT&T Bell Laboratories.
 */
