LIBRARY_GROUP_EXPORTS

LIBRARY_GROUP_COMPONENTS

	$ROOT/src/lib/std/stdlib.make6
	$ROOT/src/app/yacc/lib/mythryl-yacc-lib.make6

	fol.lex
	fol.grammar

	deep-syntax.pkg

	interface.pkg

	parse.pkg
	link.pkg


