#!/bin/sh
#
#set -x

X_KIT_HOME="/home/jhr/sml/x-kit"
export X_KIT_HOME

FILES="\
    mit/black			BlackBM		black-bm.pkg \
    mit/boxes			BoxesBM		boxes-bm.pkg \
    mit/calculator		CalcBM		calc-bm.pkg \
    mit/cross_weave		CrossWeaveBM	cross-weave-bm.pkg \
    mit/dimple1 \
    mit/dimple3			DimpleBM	dimple-bm.pkg \
    mit/dot			DotBM		dot-bm.pkg \
    mit/dots1x1 \
    mit/dots2x2			DotsBM		dots-bm.pkg \
    mit/dropbar7
    mit/dropbar8		DropBarBM	dropbar-bm.pkg \
    mit/escherknot		EscherKnotBM	escherknot-bm.pkg \
    mit/flagdown \
    mit/flagup			FlagBM		flag-bm.pkg \
    mit/flipped_gray \
    mit/gray1 \
    mit/gray3 \
    mit/light_gray 		GrayBM		gray-bm.pkg \
    mit/hlines2 \
    mit/hlines3			HLinesBM	hlines-bm.pkg \
    mit/icon			IconBM		icon-bm.pkg \
    mit/keyboard16		Keyboard16BM	keyboard16-bm.pkg \
    mit/letters			LettersBM	letters-bm.pkg \
    mit/mensetmanus		MensetmanusBM	mensetmanus-bm.pkg \
    mit/menu8 \
    mit/menu10 \
    mit/menu12 \
    mit/menu16			MenuBM		menu-bm.pkg \
    mit/noletters		NoLettersBM	noletters-bm.pkg \
    mit/plaid			PlaidBM		plaid-bm.pkg \
    mit/root_weave		RootWeaveBM	root-weave-bm.pkg \
    mit/scales			ScalesBM	scales-bm.pkg \
    mit/sipb			SipbBM		sipb-bm.pkg \
    mit/stipple			StippleBM	stipple-bm.pkg \
    mit/target			TargetBM	target-bm.pkg \
    mit/xterm			XTermBM		xterm-bm.pkg \
    mit/tie_fighter		TieFighterBM	tie_fighter-bm.pkg \
    mit/vlines2	\
    mit/vlines3			VLinesBM	vlines-bm.pkg \
    mit/weird_size		WeirdSizeBM	weird_size-bm.pkg \
    mit/wide_weave		WideWeaveBM	wide-weave-bm.pkg \
    mit/wingdogs		WingDogsBM	wingdogs-bm.pkg \
    mit/woman			WomanBM		woman-bm.pkg \
    mit/xfd_icon		XFDIconBM	xfd-icon-bm.pkg \
    mit/xlogo11			XLogo11BM	xlogo11-bm.pkg \
    mit/xlogo16			XLogo16BM	xlogo16-bm.pkg \
    mit/xlogo32			XLogo32BM	xlogo32-bm.pkg \
    mit/xlogo64			XLogo64BM	xlogo64-bm.pkg \
    mit/cntr_ptr \
    mit/cntr_ptrmsk		CenterPtrBM	center-ptr-bm.pkg \
    mit/left_ptr \
    mit/left_ptrmsk		LeftPtrBM	left-ptr-bm.pkg \
    mit/mailempty \
    mit/mailemptymsk		MailEmptyBM	mailempty-bm.pkg\
    mit/mailfull \
    mit/mailfullmsk		MailFullBM	mailful-bm.pkg \
    mit/opendot \
    mit/opendotMask		OpenDotBM	opendot-bm.pkg \
    mit/right_ptr \
    mit/right_ptrmsk		RightPtrBM	right-ptr-bm.pkg \
    mit/star \
    mit/starMask		StarBM		star-bm.pkg \
  "

STRUCT_NAME=""
IN_FILES=""
for i in $FILES
do
  case $i in
    mit/*)
      IN_FILES="$IN_FILES $i"
      ;;
    *BM) # the name of the structure
      STRUCT_NAME=$i
      ;;
    *.sml)
      echo "bm2mlx -v -s -o $i -struct $STRUCT_NAME $IN_FILES"
      ../tools/bm2mlx -v -s -o $i -struct $STRUCT_NAME $IN_FILES
      STRUCT_NAME=""
      IN_FILES=""
      ;;
    *)
      echo "unexpected name $i"
      exit
      ;;
  esac
done
