#!/bin/sh
#
# Install-time build script for trace-threadkit.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/thread-kit/threadkit-lib/cm-descr/trace-threadkit.make6.frozen.

bin/mythryld <<EOF
    make7::freeze "src/lib/thread-kit/threadkit-lib/cm-descr/trace-threadkit.make6";
EOF

if   [ -f "src/lib/thread-kit/threadkit-lib/cm-descr/trace-threadkit.make6.frozen" ]
then
     echo "      threadkit-lib/cm-descr/build-trace:   Successfully created src/lib/thread-kit/threadkit-lib/cm-descr/trace-threadkit.make6.frozen:"
     echo "      threadkit-lib/cm-descr/build-trace:   `ls -l src/lib/thread-kit/threadkit-lib/cm-descr/trace-threadkit.make6.frozen`"
else
     echo "      threadkit-lib/cm-descr/build-trace:   Failed to create src/lib/thread-kit/threadkit-lib/cm-descr/trace-threadkit.make6.frozen"
     exit 1
fi

exit 0;
