#!/bin/sh
#
# Install-time build script for c-glue-maker.
#
# We will normally be run as a result of a toplevel "make init".
#
# Our main result is the executable bin/c-glue-maker.
#
# options:
#   -o image		-- specify the name of the heap image, "c-glue-maker"
#			   is the default.

CMD=$0

C_GLUE_MAKER="c-glue-maker"
HEAP_IMAGE=""
HERE=`pwd`
cd ../../..
THREE_UP=`pwd`
cd $HERE
BIN=${INSTALL_DIR:-$THREE_UP}/bin
MAKELIB=$BIN/build-an-executable-mythryl-heap-image

echo
echo '-------------------------------------'
echo "                  build-c-glue-maker-app:  Starting."

#
# Process command-line options:
while [ "$#" != "0" ] ; do
    arg=$1
    shift
    case $arg in
	-o)
	    if [ "$#" = "0" ]; then
		echo "                  build-c-glue-maker-app:   Must supply image name for -o option"
		exit 1
	    fi
	    HEAP_IMAGE=$1; shift
	    ;;
	*)
	    echo "                  build-c-glue-maker-app:   Invalid argument: $arg"
	    exit 1
	    ;;
    esac
done

if [ "$HEAP_IMAGE" = "" ]; then
    HEAP_IMAGE="$C_GLUE_MAKER"
fi

echo "                  build-c-glue-maker-app:   Doing:                  $MAKELIB c-glue-maker.lib main.main $HEAP_IMAGE"
$MAKELIB c-glue-maker.lib main.main $HEAP_IMAGE

if [ -f "$HEAP_IMAGE" ]; then

    echo "                  build-c-glue-maker-app:   $HEAP_IMAGE created."

    if [ -f "$BIN/$C_GLUE_MAKER" ]; then
        echo "              src/app/c-glue-maker/build:   Removing                $BIN/$C_GLUE_MAKER"
        rm $BIN/$C_GLUE_MAKER
    fi

    echo "                  build-c-glue-maker-app:   Installing              $HEAP_IMAGE as $BIN/$C_GLUE_MAKER"
    cp "$HEAP_IMAGE" "$BIN/$C_GLUE_MAKER"
    chmod +x "$BIN/$C_GLUE_MAKER"
    rm "$HEAP_IMAGE"

else
    echo "                  build-c-glue-maker-app:   $HEAP_IMAGE not created, aborting."
    exit 1
fi



echo "                  build-c-glue-maker-app:   Done."
echo
echo
echo


exit 0