#!/bin/sh
#
# Install-time build script for precedence-parser.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/compiler/back/low/tools/precedence-parser.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/compiler/back/low/tools/precedence-parser.lib";
EOF

if [ -f "src/lib/compiler/back/low/tools/precedence-parser.lib.frozen" ]
then
    echo "                 build-precedence-parser:   Successfully created    src/lib/compiler/back/low/tools/precedence-parser.lib.frozen:"
    echo "                 build-precedence-parser:                           `ls -l src/lib/compiler/back/low/tools/precedence-parser.lib.frozen`"
else
    echo "                 build-precedence-parser:   FAILED TO CREATE        src/lib/compiler/back/low/tools/precedence-parser.lib.frozen"
    exit 1
fi

exit 0;
