#!/bin/sh
#
# Install-time build script for architecture-parser.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/compiler/back/low/tools/architecture-parser.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/compiler/back/low/tools/architecture-parser.lib";
EOF

if [ -f "src/lib/compiler/back/low/tools/architecture-parser.lib.frozen" ]
then
    echo "build-architecture-description-language-parser   Successfully created    src/lib/compiler/back/low/tools/architecture-parser.lib.frozen:"
    echo "build-architecture-description-language-parser                           `ls -l src/lib/compiler/back/low/tools/architecture-parser.lib.frozen`"
else
    echo "build-architecture-description-language-parser   FAILED TO CREATE        src/lib/compiler/back/low/tools/architecture-parser.lib.frozen"
    exit 1
fi

exit 0;
