#!/bin/sh
#
# Install-time build script for make-sourcecode-for-backend-packages.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/compiler/back/low/tools/arch/make-sourcecode-for-backend-packages.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/compiler/back/low/tools/arch/make-sourcecode-for-backend-packages.lib";
EOF

if [ -f "src/lib/compiler/back/low/tools/arch/make-sourcecode-for-backend-packages.lib.frozen" ]
then
    echo "            build-architecture-generator:   Successfully created    src/lib/compiler/back/low/tools/arch/make-sourcecode-for-backend-packages.lib.frozen:"
    echo "            build-architecture-generator:                           `ls -l src/lib/compiler/back/low/tools/arch/make-sourcecode-for-backend-packages.lib.frozen`"
else
    echo "            build-architecture-generator:   FAILED TO CREATE        src/lib/compiler/back/low/tools/arch/make-sourcecode-for-backend-packages.lib.frozen"
    exit 1
fi

exit 0;
