#!/bin/sh
#
# Install-time build script for match-compiler.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/compiler/back/low/tools/match-compiler.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/compiler/back/low/tools/match-compiler.lib";
EOF

if [ -f "src/lib/compiler/back/low/tools/match-compiler.lib.frozen" ]
then
    echo "                    build-match-compiler:   Successfully created    src/lib/compiler/back/low/tools/match-compiler.lib.frozen:"
    echo "                    build-match-compiler:                           `ls -l src/lib/compiler/back/low/tools/match-compiler.lib.frozen`"
else
    echo "                    build-match-compiler:   FAILED TO CREATE        src/lib/compiler/back/low/tools/match-compiler.lib.frozen"
    exit 1
fi

exit 0;
