#!/bin/sh
#
# Install-time build script for line-number-database.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/compiler/back/low/tools/line-number-database.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/compiler/back/low/tools/line-number-database.lib";
EOF

if [ -f "src/lib/compiler/back/low/tools/line-number-database.lib.frozen" ]
then
    echo "                        build-source-map:   Successfully created    src/lib/compiler/back/low/tools/line-number-database.lib.frozen:"
    echo "                        build-source-map:                           `ls -l src/lib/compiler/back/low/tools/line-number-database.lib.frozen`"
else
    echo "                        build-source-map:   FAILED TO CREATE        src/lib/compiler/back/low/tools/line-number-database.lib.frozen"
    exit 1
fi

exit 0;
