#!/bin/sh
#
# Install-time build script for sml-ast.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/compiler/back/low/tools/sml-ast.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/compiler/back/low/tools/sml-ast.lib";
EOF

if [ -f "src/lib/compiler/back/low/tools/sml-ast.lib.frozen" ]
then
    echo "                           build-sml-ast:   Successfully created    src/lib/compiler/back/low/tools/sml-ast.lib.frozen:"
    echo "                           build-sml-ast:                           `ls -l src/lib/compiler/back/low/tools/sml-ast.lib.frozen`"
else
    echo "                           build-sml-ast:   FAILED TO CREATE        src/lib/compiler/back/low/tools/sml-ast.lib.frozen"
    exit 1
fi

exit 0;
