#!/bin/sh
#
# Install-time build script for regex-lib.make6. THIS SHOULD BE OBSOLETE SINCE regex-lib.make6 got merged into lib7.make6
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/regex/regex-lib.make6.frozen.

bin/mythryld <<EOF
    make7::freeze "src/lib/regex/regex-lib.make6";
EOF

if   [ -f "src/lib/regex/regex-lib.make6.frozen" ]
then
     echo "                     src/lib/regex/build:   Successfully created src/lib/regex/regex-lib.make6.frozen:"
     echo "                     src/lib/regex/build:   `ls -l src/lib/regex/regex-lib.make6.frozen`"
else
     echo "                     src/lib/regex/build:   Failed to create src/lib/regex/regex-lib.make6.frozen"
     exit 1
fi

exit 0;
