#!/bin/sh
#
# Install-time build script for regex-lib.lib. THIS SHOULD BE OBSOLETE SINCE regex-lib.lib got merged into lib7.lib
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/regex/regex-lib.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/regex/regex-lib.lib";
EOF

if [ -f "src/lib/regex/regex-lib.lib.frozen" ]
then
    echo "                     src/lib/regex/build:   Successfully created    src/lib/regex/regex-lib.lib.frozen:"
    echo "                     src/lib/regex/build:                           `ls -l src/lib/regex/regex-lib.lib.frozen`"
else
    echo "                     src/lib/regex/build:   FAILED TO CREATE        src/lib/regex/regex-lib.lib.frozen"
    exit 1
fi

exit 0;
