#!/bin/sh
#
# Install-time build script for ml-burg.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the executable bin/ml-burg.
#
# options:
#   -o image		-- specify the name of the heap image, "ml-burg"
#			   is the default.

CMD=$0

ML_BURG="ml-burg"
HEAP_IMAGE=""
HERE=`pwd`
cd ../../..
THREE_UP=`pwd`
cd $HERE
BIN=${INSTALL_DIR:-$THREE_UP}/bin
MAKE7=$BIN/build-an-executable-mythryl-heap-image

echo
echo '---------------------------------'
echo "src/app/burg/build:  Starting."

#
# Process command-line options:
while [ "$#" != "0" ] ; do
    arg=$1
    shift
    case $arg in
	-o)
	    if [ "$#" = "0" ]; then
		echo "src/app/burg/build:   Must supply image name for -o option"
		exit 1
	    fi
	    HEAP_IMAGE=$1; shift
	;;
	*)
	    echo "src/app/burg/build:  Invalid argument: $arg"
	    exit 1
	    ;;
    esac
done

if [ "$HEAP_IMAGE" = "" ]; then
    HEAP_IMAGE="$ML_BURG"
fi

echo "src/app/burg/build doing:   $MAKE7 Ml-Burg.make6 main.main $HEAP_IMAGE"
"$MAKE7" Ml-Burg.make6 main.main $HEAP_IMAGE

if [ -f "$HEAP_IMAGE" ]; then

    echo "                      src/app/burg/build:   $HEAP_IMAGE created."

    if [ -f "$BIN/$ML_BURG.old" ]; then
        echo "                      src/app/burg/build:   Removing $BIN/$ML_BURG.old"
        rm $BIN/$ML_BURG.old
    fi

    if [ -f "$BIN/$ML_BURG" ]; then
        echo "                      src/app/burg/build:   Saving $BIN/$ML_BURG as $BIN/$ML_BURG.old"
        mv "$BIN/$ML_BURG" "$BIN/$ML_BURG.old"
    fi

    echo "                      src/app/burg/build:   Installing $HEAP_IMAGE as $BIN/$ML_BURG"
    cp "$HEAP_IMAGE" "$BIN/$ML_BURG"
    chmod +x "$BIN/$ML_BURG"
    rm "$HEAP_IMAGE"

else
    echo "                      src/app/burg/build:   $HEAP_IMAGE not created, aborting."
    exit 1
fi



echo "src/app/burg/build:  Done."
echo
echo
echo

exit 0
