
LIBRARY_EXPORTS

	api POLY_GEN
	api REWRITE_GEN

	pkg RewriterGen

	generic PolyGen
	generic RewriteGen



LIBRARY_COMPONENTS

        $ROOT/src/lib/std/stdlib.make6

	$ROOT/src/lib/core/lower/control.make6

	$ROOT/src/lib/compiler/backend/lower/tools/source-map/Makefile.make6
	$ROOT/src/lib/compiler/backend/lower/tools/fake-sml-ast/Makefile.make6 		# The fake SML abstract syntax.
	$ROOT/src/lib/compiler/backend/lower/tools/prettyprint/Makefile.make6  		# Pretty printer utilities.
	$ROOT/src/lib/compiler/backend/lower/tools/parser/Makefile.make6     			# Parser.

	poly-gen.api
	poly-g.pkg
	rewrite-gen.api
	rewrite-g.pkg
	glue.pkg
