#!/bin/sh
#
# Install-time build script for mythryl-yacc.
#
# We will normally be run as a result of a toplevel "make rest"
#
# Our main result is the executable bin/mythryl-yacc.
#
# options:
#   -o image		-- specify the name of the heap image, "mythryl-yacc"
#			   is the default.

CMD=$0

MYTHRYL_YACC="mythryl-yacc"
HEAP_IMAGE=""
HERE=`pwd`
cd ../../..
THREE_UP=`pwd`
cd $HERE
BIN=${INSTALL_DIR:-$THREE_UP}/bin
MAKE7=$BIN/build-an-executable-mythryl-heap-image

echo
echo '-----------------------------------------------------'
echo "                   src/app/yacc/build:   Starting."

#
# Process command-line options:
while [ "$#" != "0" ] ; do
    arg=$1
    shift
    case $arg in
	-o)
	    if [ "$#" = "0" ]; then
		echo "                   src/app/yacc/build:   Must supply image name for -o option"
		exit 1
	    fi
	    HEAP_IMAGE=$1; shift
	    ;;
	*)
	    echo "                   src/app/yacc/build:   Invalid argument: $arg"
	    exit 1
	    ;;
    esac
done

if [ "$HEAP_IMAGE" = "" ]; then
    HEAP_IMAGE="$MYTHRYL_YACC"
fi

echo "                      src/app/yacc/build:   Entering `pwd`/src"
cd src

echo "                   src/app/yacc/build:   Doing:                  $MAKE7 Mythryl-Yacc.make6 export_parse_fn::parse_fn $HEAP_IMAGE"
"$MAKE7" Mythryl-Yacc.make6 export_parse_fn::parse_fn "$HEAP_IMAGE"

if [ -f "$HEAP_IMAGE" ]; then

    echo "                      src/app/yacc/build:   $HEAP_IMAGE created."

    if [ -f "$BIN/$MYTHRYL_YACC.old" ]; then
        echo "                      src/app/yacc/build:   Removing $BIN/$MYTHRYL_YACC.old"
        rm $BIN/$MYTHRYL_YACC.old
    fi

    if [ -f "$BIN/$MYTHRYL_YACC" ]; then
        echo "                      src/app/yacc/build:   Saving $BIN/$MYTHRYL_YACC as $BIN/$MYTHRYL_YACC.old"
        mv "$BIN/$MYTHRYL_YACC" "$BIN/$MYTHRYL_YACC.old"
    fi

    echo "                      src/app/yacc/build:   Installing $HEAP_IMAGE as $BIN/$MYTHRYL_YACC"
    cp "$HEAP_IMAGE" "$BIN/$MYTHRYL_YACC"
    chmod +x "$BIN/$MYTHRYL_YACC"
    rm "$HEAP_IMAGE"

else
    echo "Error:                src/app/yacc/build:   $HEAP_IMAGE not created, aborting."
    exit 1
fi


echo "                      src/app/yacc/build:   Done."
echo
echo
echo


exit 0
