#!/bin/sh
#
# Install-time build script for widgets.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/x-kit/tut/widget/widgets.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/x-kit/tut/widget/widgets.lib";
EOF

if [ -f "src/lib/x-kit/tut/widget/widgets.lib.frozen" ]
then
    echo "                           build-widgets:   Successfully created    src/lib/x-kit/tut/widget/widgets.lib.frozen:"
    echo "                           build-widgets:                           `ls -l src/lib/x-kit/tut/widget/widgets.lib.frozen`"
else
    echo "                           build-widgets:   Failed to create src/lib/x-kit/tut/widget/widgets.lib.frozen"
    exit 1
fi

exit 0;
