#!/bin/sh
#
# Install-time build script for triangle-app.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/x-kit/tut/triangle/triangle-app.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/x-kit/tut/triangle/triangle-app.lib";
EOF

if [ -f "src/lib/x-kit/tut/triangle/triangle-app.lib.frozen" ]
then
    echo "                      build-triangle-app:   Successfully created    src/lib/x-kit/tut/triangle/triangle-app.lib.frozen:"
    echo "                      build-triangle-app:                           `ls -l src/lib/x-kit/tut/triangle/triangle-app.lib.frozen`"
else
    echo "                      build-triangle-app:   FAILED TO CREATE        src/lib/x-kit/tut/triangle/triangle-app.lib.frozen"
    exit 1
fi

exit 0;
