#!/bin/sh
#
# Install-time build script for threadkit-internal.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/thread-kit/src/threadkit-internal.make6.frozen.

bin/mythryld <<EOF
    make7::freeze "src/lib/thread-kit/src/threadkit-internal.make6";
EOF

if   [ -f "src/lib/thread-kit/src/threadkit-internal.make6.frozen" ]
then
     echo "        .../src/build-threadkit-internal:   Successfully created src/lib/thread-kit/src/threadkit-internal.make6.frozen:"
     echo "        .../src/build-threadkit-internal:   `ls -l src/lib/thread-kit/src/threadkit-internal.make6.frozen`"
else
     echo "        .../src/build-threadkit-internal:   Failed to create src/lib/thread-kit/src/threadkit-internal.make6.frozen"
     exit 1
fi

exit 0;
