#!/bin/sh
#
# Use autoconf and kith to generate ./Configure, ./config.h ...
# from input files ./Configure.in, ./config.h.in, ./aclocal.m4 ...
#
# This script is typically invoked by doing
#
#    'make gnu-autotools-output
#
# in the distribution root directory.
#
autoconf Configure.in >Configure
chmod +x Configure
