// mythryl-config.h
//
// The architectural idea here is to have
//
//     config.h
//
// (which is autogenerated by the GNU autoconfig toolset)
// record which resources are available on the build machine,
// and then record in this file manual policy decisions such
// as whether to take advantage of a given resource.
//
// Thus, we #include config.h here, and then #include (only)
//
//     mythryl-config.h
//
// in all our C source files.
//
// By convention symbols defined in config.h start with the prefix
//
//     HAVE_
//
// whereas symbols defined in mythryl-config.h start with the prefix
//
//     WANT_
//
//                -- 2011-10-28 CrT

#ifndef MYTHRYL_CONFIG_H
#define MYTHRYL_CONFIG_H 1

#include "config.h"

// Define this as TRUE (nonzero) to compile in support
// for multiple posix threads running Mythryl code in
// parallel in the same address space.  For background
// see    src/A.MULTICORE-SUPPORT.OVERVIEW
//
#define WANT_PTHREAD_SUPPORT 0

// Max number of posix threads running Mythryl.
// We dedicate half a meg or so of memory to each
// one, so don't be prolifigate here:
//
#if !WANT_PTHREAD_SUPPORT
    //
    #define MAX_PTHREADS	1
#else
    #define MAX_PTHREADS	8
#endif


#endif // MYTHRYL_CONFIG_H
