#!/bin/sh
#
# Install-time build script for reactive.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/reactive/reactive.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/reactive/reactive.lib";
EOF

if [ -f "src/lib/reactive/reactive.lib.frozen" ]
then
    echo "                      build-reactive-lib:   Successfully created    src/lib/reactive/reactive.lib.frozen:"
    echo "                      build-reactive-lib:                           `ls -l src/lib/reactive/reactive.lib.frozen`"
else
    echo "                      build-reactive-lib:   FAILED TO CREATE        src/lib/reactive/reactive.lib.frozen"
    exit 1
fi

exit 0;
