#!/usr/bin/perl
## usage: makeallcm 
## 
## This script looks at ALL.make7 and create all the Make7 files.
##

$SPECIAL_CM{"lib7.make7"} = 1;
$SPECIAL_CM{"mythryl-yacc-lib.make7"} = 1;

makeallcm("ALL.make7");

sub makeallcm
{  my($cmfile) = @_;
   $new = 1;
   open(LOWCODE,$cmfile) || die ("$!: $cmfile\n");

   while (<LOWCODE>)
   {  push @FOOTER, $_;
      next if $_ =~ /\(\*.*\*\)/;
      next if $_ =~ /^\s*$/;
      ($comment=1, next) if $_ =~ /^\s*\(\*.*/;
      ($comment=0, next) if $_ =~ /^.*\*\)/;
      next if $comment;
      if (/^(.*):$/)
      {  finish();
         $outfile = $1;
         open(OUT,">$outfile") || die("$!: $outfile\n");
         print STDERR "[$outfile]";
         print OUT <<"END";
(* This file is created by makeallcm *)
Library
is
END
         next;  
      }   
      if (/^\s*(.*\.make7)\s*$/)
      {  push @CMFILES, $1;
         next; 
      } 
      if ($new) { dumpCMfiles(); }
      print OUT $_;
   }
   finish();
}
sub finish
{  close(OUT);
   @CMFILES=();
   $new = 1;
   if ($outfile)
   { system("perl makecm $outfile");
   }
}

sub dumpCMfiles()
{  print OUT <<"END";
#if LIB7_VERSION * 100 + LIB7_MINOR_VERSION >= 11030
	\$ROOT/src/lib/std/stdlib.make7
END
   foreach $f (@CMFILES) {  print OUT "\t\$/$f\n"; }
   print OUT "#else\n";
   print OUT "\tbasis.make7\n";
   foreach $f (@CMFILES) {  print OUT "\t$f\n"; }
   print OUT "#endif\n#else\n";
   foreach $f (@CMFILES) {  print OUT "\t$f\n"; }
   @CMFILES=();
   $new = 0;
}
