#!/bin/sh
#
# Install-time build script for c.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/c-glue-lib/c.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/c-glue-lib/c.lib";
EOF

if [ -f "src/lib/c-glue-lib/c.lib.frozen" ]
then
    echo "                src/lib/c-glue-lib/build:   Successfully created    src/lib/c-glue-lib/c.lib.frozen:"
    echo "                src/lib/c-glue-lib/build:                           `ls -l src/lib/c-glue-lib/c.lib.frozen`"
else
    echo "                src/lib/c-glue-lib/build:   FAILED TO CREATE        src/lib/c-glue-lib/c.lib.frozen"
    exit 1
fi

exit 0;
