LIBRARY_GROUP_EXPORTS

LIBRARY_GROUP_COMPONENTS

        ../../ast/Makefile.make6

	../copy/copy-ast.api
	../copy/copy-ast.pkg

	simplify-ast.api
	simplify-ast.pkg

	#if (defined(d))
        extensions/d/eq-ast-ext.pkg
	#else
        extensions/c/copy-ast-ext.pkg
        extensions/c/simplify-ast-ext.pkg

	#endif
