#!/bin/sh
#
# Install-time build script for c-kit.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/c-kit/src/c-kit.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/c-kit/src/c-kit.lib";
EOF

if [ -f "src/lib/c-kit/src/c-kit.lib.frozen" ]
then
    echo "                 src/lib/c-kit/src/build:   Successfully created    src/lib/c-kit/src/c-kit.lib.frozen:"
    echo "                 src/lib/c-kit/src/build:                           `ls -l src/lib/c-kit/src/c-kit.lib.frozen`"
else
    echo "                 src/lib/c-kit/src/build:   FAILED TO CREATE        src/lib/c-kit/src/c-kit.lib.frozen"
    exit 1
fi

exit 0;
