#!/bin/sh
#
# Install-time build script for mythryl-lex.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the executable bin/mythryl-lex.
#
# options:
#   -o image		-- specify the name of the heap image, "mythryl-lex"
#			   is the default.

CMD=$0

MYTHRYL_LEX="mythryl-lex"
HEAP_IMAGE=""
HERE=`pwd`
cd ../../..
THREE_UP=`pwd`
cd $HERE
BIN=${INSTALL_DIR:-$THREE_UP}/bin
BUILD=$BIN/build-an-executable-mythryl-heap-image

echo
echo '----------------------------'
echo "                       src/app/lex/build:  Starting."

#
# Process command-line options:
while [ "$#" != "0" ] ; do
    arg=$1
    shift
    case $arg in
	-o)
	    if [ "$#" = "0" ]; then
		echo "                       src/app/lex/build:   Must supply image name for -o option"
		exit 1
	    fi
	    HEAP_IMAGE=$1; shift
	    ;;
	*)
	    echo "                       src/app/lex/build:   Invalid argument: $arg"
	    exit 1
	    ;;
    esac
done

if [ "$HEAP_IMAGE" = "" ]; then
    HEAP_IMAGE="$MYTHRYL_LEX"
fi

echo "src/app/lex/build doing:   $BUILD mythryl-lex.make6 export_lex_fn::lex_fn $HEAP_IMAGE"
"$BUILD" mythryl-lex.make6 export_lex_fn::lex_fn $HEAP_IMAGE

if [ -f "$HEAP_IMAGE" ]; then

    echo "                       src/app/lex/build:   $HEAP_IMAGE created."

    if [ -f "$BIN/$MYTHRYL_LEX.old" ]; then
        echo "                       src/app/lex/build:   Removing $BIN/$MYTHRYL_LEX.old"
        rm $BIN/$MYTHRYL_LEX.old
    fi

    if [ -f "$BIN/$MYTHRYL_LEX" ]; then
        echo "                       src/app/lex/build:   Saving $BIN/$MYTHRYL_LEX as $BIN/$MYTHRYL_LEX.old"
        mv "$BIN/$MYTHRYL_LEX" "$BIN/$MYTHRYL_LEX.old"
    fi

    echo "                       src/app/lex/build:   Installing $HEAP_IMAGE as $BIN/$MYTHRYL_LEX"
    cp "$HEAP_IMAGE" "$BIN/$MYTHRYL_LEX"
    chmod +x "$BIN/$MYTHRYL_LEX"
    rm "$HEAP_IMAGE"

else
    echo "                       src/app/lex/build:   $HEAP_IMAGE not created, aborting."
    exit 1
fi


echo "                       src/app/lex/build:   Done."
echo
echo
echo

exit 0