
LIBRARY_EXPORTS

	api PRECEDENCE_PARSER
	pkg PrecedenceParser



LIBRARY_COMPONENTS

        $ROOT/src/lib/std/stdlib.make6

	$ROOT/src/lib/compiler/backend/lower/tools/source-map/Makefile.make6

	prec-parse.pkg
