#!/bin/sh
#
# Install-time build script for bitmap-editor.lib.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/x-kit/tut/bitmap-editor/bitmap-editor.lib.frozen.

bin/mythryld <<EOF
    makelib::freeze "src/lib/x-kit/tut/bitmap-editor/bitmap-editor.lib";
EOF

if   [ -f "src/lib/x-kit/tut/bitmap-editor/bitmap-editor.lib.frozen" ]
then
    echo "                     build-bitmap-editor:   Successfully created    src/lib/x-kit/tut/bitmap-editor/bitmap-editor.lib.frozen:"
    echo "                     build-bitmap-editor:                           `ls -l src/lib/x-kit/tut/bitmap-editor/bitmap-editor.lib.frozen`"
else
    echo "                     build-bitmap-editor:   FAILED TO CREATE        src/lib/x-kit/tut/bitmap-editor/bitmap-editor.lib.frozen"
    exit 1
fi

exit 0;
