#!/bin/sh
#
# Install the stabilized libraries into your sml distribution. 
#
# Usage: install-lib <targetname>
#

TARGET=$1; shift
if [ ! -d $TARGET ]; then
   echo "Directory $TARGET not found"; exit 1
fi
if [ ! -f $TARGET/.stable -a $TARGET != common ]; then 
   echo "Warning: $TARGET has not been properly stabilized.  I'm ignoring it"
   exit 0
fi
if [ ! -f config/config ]; then
   echo "File config/config is not found"
   echo "Have you run Configure?"
   exit 1
fi
. config/config
if [ ! -d "$SMLDIST" ]; then
   echo "Can't find the SML distributation directory $SMLDIST"
   exit 1
fi
echo "[Installing $TARGET]"

#
# Find all stabilized cm files
#
CMFILES=`find $TARGET -name '*.cm' | egrep '/CM/'` 

#
# Copy them to the right place
# Should we do it destructively?
#
TARGETDIR=$SMLDIST/lib/smlnj-ffilib
for f in $CMFILES ; do 
   dst=$TARGETDIR/$f
   dstdir=`dirname $dst`
   mkdir -p $dstdir # create the directory if it doesn't exists
   #echo "[Copying $f ==> $dst]"
   cp -f $f $dst
done

tmpfile=/tmp/pathconfig.tmp.$$
trap 'rm -f $tmpfile; exit 1' 1 2 3 15

PATHCONFIG=$SMLDIST/lib/pathconfig
if [ ! -f $PATHCONFIG ]; then
   echo "No $SMLDIST/lib/pathconfig"
   echo "Something is broken in your SML distribution"
   exit 1
fi

#
# Add to pathconfig
#
grep -l smlnj-ffilib $PATHCONFIG >/dev/null
if [ $? != 0 ] ; then
   echo "Adding the entry smlnj-ffilib to pathconfig"
   echo "smlnj-ffilib smlnj-ffilib" >$tmpfile
   cat $PATHCONFIG >> $tmpfile
   sort $tmpfile > $PATHCONFIG
fi
rm -f $tmpfile
exit 0
