#!/bin/sh
#
# make-lib: <shared library> 

if [ "$1" = `basename $1` ]; then
   LIBPATH=`(cd ../lib; pwd)`
   NAME=$1
   NAME=`echo $NAME | sed -e 's/^libsmlsml/libsml/'`
   NAME=`echo $NAME | sed -e 's/-//g'`
   LIBPATH=$LIBPATH/$NAME;
else
   LIBPATH=$1;
fi

cat <<EOF
structure Library = Library 
  (val LIBPATH = "$LIBPATH")
EOF
