#!/bin/sh
#
# Create a new target file from all the directories
# Require rpm.
#


bar() {
echo \
'##############################################################################'
}

(cd ..;

cat <<EOF
###############################################################################
#
#  This file is use to select the libraries that you want to build on your
#  target platform.  By default, everything that compiles on my machine 
#  -- intel32 (x86) Linux -- is selected.  
#  Please comment out the targets that you do not want.
#
###############################################################################

EOF

for dir in `ls -1 | sort`; do
   case $dir in
     ffi-packager|lib|ml-grinder|common|c-interoperability)
        ;;
     *)
      if [ -f $dir/Makefile -a -f $dir/make.pkg ]; then
          OK=1
          bar
          (cd $dir; make describe) |\
          perl -p -e 's/Build Date:.*//; s/^Install date:.*\n//; s/(Source RPM:.*)/\n\1/' |\
          sed -e 's/^/# /'
          if [ -f $dir/NOTES ]; then
             echo "#"
             echo "# Notes:"
             sed -e 's/^/# /' < $dir/NOTES
          fi
          if [ -f $dir/PROBLEMS ]; then
             echo "#"
             echo "# Problems:"
             sed -e 's/^/# /' < $dir/PROBLEMS
             OK=0
          fi
          bar 
          if [ $OK = 1 ] ; then
             echo 'TARGETS="$TARGETS '$dir'"'
          else
             echo '#TARGETS="$TARGETS '$dir'" # disabled because of problems'
          fi
          echo
      fi
      ;;
   esac
done)
